// Dados completos dos elementos químicos da tabela periódica
const elementsData = [
    {
        number: 1,
        symbol: "H",
        name: "Hidrogênio",
        mass: "1.008",
        category: "nonmetal",
        config: "1s¹",
        state: "Gás",
        density: "0.08988 g/L",
        melting: "-259.14°C",
        boiling: "-252.87°C",
        row: 1,
        col: 1
    },
    {
        number: 2,
        symbol: "He",
        name: "Hélio",
        mass: "4.003",
        category: "noble-gas",
        config: "1s²",
        state: "Gás",
        density: "0.1786 g/L",
        melting: "-272.2°C",
        boiling: "-268.93°C",
        row: 1,
        col: 18
    },
    {
        number: 3,
        symbol: "Li",
        name: "Lítio",
        mass: "6.941",
        category: "alkali-metal",
        config: "[He] 2s¹",
        state: "Sólido",
        density: "0.534 g/cm³",
        melting: "180.5°C",
        boiling: "1342°C",
        row: 2,
        col: 1
    },
    {
        number: 4,
        symbol: "Be",
        name: "Berílio",
        mass: "9.012",
        category: "alkaline-earth-metal",
        config: "[He] 2s²",
        state: "Sólido",
        density: "1.85 g/cm³",
        melting: "1287°C",
        boiling: "2469°C",
        row: 2,
        col: 2
    },
    {
        number: 5,
        symbol: "B",
        name: "Boro",
        mass: "10.811",
        category: "metalloid",
        config: "[He] 2s² 2p¹",
        state: "Sólido",
        density: "2.34 g/cm³",
        melting: "2075°C",
        boiling: "4000°C",
        row: 2,
        col: 13
    },
    {
        number: 6,
        symbol: "C",
        name: "Carbono",
        mass: "12.011",
        category: "nonmetal",
        config: "[He] 2s² 2p²",
        state: "Sólido",
        density: "2.267 g/cm³",
        melting: "3550°C",
        boiling: "4027°C",
        row: 2,
        col: 14
    },
    {
        number: 7,
        symbol: "N",
        name: "Nitrogênio",
        mass: "14.007",
        category: "nonmetal",
        config: "[He] 2s² 2p³",
        state: "Gás",
        density: "1.251 g/L",
        melting: "-210.1°C",
        boiling: "-195.79°C",
        row: 2,
        col: 15
    },
    {
        number: 8,
        symbol: "O",
        name: "Oxigênio",
        mass: "15.999",
        category: "nonmetal",
        config: "[He] 2s² 2p⁴",
        state: "Gás",
        density: "1.429 g/L",
        melting: "-218.79°C",
        boiling: "-182.95°C",
        row: 2,
        col: 16
    },
    {
        number: 9,
        symbol: "F",
        name: "Flúor",
        mass: "18.998",
        category: "halogen",
        config: "[He] 2s² 2p⁵",
        state: "Gás",
        density: "1.696 g/L",
        melting: "-219.67°C",
        boiling: "-188.11°C",
        row: 2,
        col: 17
    },
    {
        number: 10,
        symbol: "Ne",
        name: "Neônio",
        mass: "20.180",
        category: "noble-gas",
        config: "[He] 2s² 2p⁶",
        state: "Gás",
        density: "0.9 g/L",
        melting: "-248.59°C",
        boiling: "-246.05°C",
        row: 2,
        col: 18
    },
    {
        number: 11,
        symbol: "Na",
        name: "Sódio",
        mass: "22.990",
        category: "alkali-metal",
        config: "[Ne] 3s¹",
        state: "Sólido",
        density: "0.971 g/cm³",
        melting: "97.79°C",
        boiling: "883°C",
        row: 3,
        col: 1
    },
    {
        number: 12,
        symbol: "Mg",
        name: "Magnésio",
        mass: "24.305",
        category: "alkaline-earth-metal",
        config: "[Ne] 3s²",
        state: "Sólido",
        density: "1.738 g/cm³",
        melting: "650°C",
        boiling: "1090°C",
        row: 3,
        col: 2
    },
    {
        number: 13,
        symbol: "Al",
        name: "Alumínio",
        mass: "26.982",
        category: "post-transition-metal",
        config: "[Ne] 3s² 3p¹",
        state: "Sólido",
        density: "2.698 g/cm³",
        melting: "660.32°C",
        boiling: "2519°C",
        row: 3,
        col: 13
    },
    {
        number: 14,
        symbol: "Si",
        name: "Silício",
        mass: "28.086",
        category: "metalloid",
        config: "[Ne] 3s² 3p²",
        state: "Sólido",
        density: "2.329 g/cm³",
        melting: "1414°C",
        boiling: "3265°C",
        row: 3,
        col: 14
    },
    {
        number: 15,
        symbol: "P",
        name: "Fósforo",
        mass: "30.974",
        category: "nonmetal",
        config: "[Ne] 3s² 3p³",
        state: "Sólido",
        density: "1.82 g/cm³",
        melting: "44.15°C",
        boiling: "280.5°C",
        row: 3,
        col: 15
    },
    {
        number: 16,
        symbol: "S",
        name: "Enxofre",
        mass: "32.065",
        category: "nonmetal",
        config: "[Ne] 3s² 3p⁴",
        state: "Sólido",
        density: "2.067 g/cm³",
        melting: "115.21°C",
        boiling: "444.61°C",
        row: 3,
        col: 16
    },
    {
        number: 17,
        symbol: "Cl",
        name: "Cloro",
        mass: "35.453",
        category: "halogen",
        config: "[Ne] 3s² 3p⁵",
        state: "Gás",
        density: "3.214 g/L",
        melting: "-101.5°C",
        boiling: "-34.04°C",
        row: 3,
        col: 17
    },
    {
        number: 18,
        symbol: "Ar",
        name: "Argônio",
        mass: "39.948",
        category: "noble-gas",
        config: "[Ne] 3s² 3p⁶",
        state: "Gás",
        density: "1.784 g/L",
        melting: "-189.35°C",
        boiling: "-185.85°C",
        row: 3,
        col: 18
    },
    {
        number: 19,
        symbol: "K",
        name: "Potássio",
        mass: "39.098",
        category: "alkali-metal",
        config: "[Ar] 4s¹",
        state: "Sólido",
        density: "0.862 g/cm³",
        melting: "63.5°C",
        boiling: "759°C",
        row: 4,
        col: 1
    },
    {
        number: 20,
        symbol: "Ca",
        name: "Cálcio",
        mass: "40.078",
        category: "alkaline-earth-metal",
        config: "[Ar] 4s²",
        state: "Sólido",
        density: "1.54 g/cm³",
        melting: "842°C",
        boiling: "1484°C",
        row: 4,
        col: 2
    },
    {
        number: 21,
        symbol: "Sc",
        name: "Escândio",
        mass: "44.956",
        category: "transition-metal",
        config: "[Ar] 3d¹ 4s²",
        state: "Sólido",
        density: "2.989 g/cm³",
        melting: "1541°C",
        boiling: "2836°C",
        row: 4,
        col: 3
    },
    {
        number: 22,
        symbol: "Ti",
        name: "Titânio",
        mass: "47.867",
        category: "transition-metal",
        config: "[Ar] 3d² 4s²",
        state: "Sólido",
        density: "4.506 g/cm³",
        melting: "1668°C",
        boiling: "3287°C",
        row: 4,
        col: 4
    },
    {
        number: 23,
        symbol: "V",
        name: "Vanádio",
        mass: "50.942",
        category: "transition-metal",
        config: "[Ar] 3d³ 4s²",
        state: "Sólido",
        density: "6.11 g/cm³",
        melting: "1910°C",
        boiling: "3407°C",
        row: 4,
        col: 5
    },
    {
        number: 24,
        symbol: "Cr",
        name: "Cromo",
        mass: "51.996",
        category: "transition-metal",
        config: "[Ar] 3d⁵ 4s¹",
        state: "Sólido",
        density: "7.15 g/cm³",
        melting: "1907°C",
        boiling: "2671°C",
        row: 4,
        col: 6
    },
    {
        number: 25,
        symbol: "Mn",
        name: "Manganês",
        mass: "54.938",
        category: "transition-metal",
        config: "[Ar] 3d⁵ 4s²",
        state: "Sólido",
        density: "7.44 g/cm³",
        melting: "1246°C",
        boiling: "2061°C",
        row: 4,
        col: 7
    },
    {
        number: 26,
        symbol: "Fe",
        name: "Ferro",
        mass: "55.845",
        category: "transition-metal",
        config: "[Ar] 3d⁶ 4s²",
        state: "Sólido",
        density: "7.874 g/cm³",
        melting: "1538°C",
        boiling: "2861°C",
        row: 4,
        col: 8
    },
    {
        number: 27,
        symbol: "Co",
        name: "Cobalto",
        mass: "58.933",
        category: "transition-metal",
        config: "[Ar] 3d⁷ 4s²",
        state: "Sólido",
        density: "8.86 g/cm³",
        melting: "1495°C",
        boiling: "2927°C",
        row: 4,
        col: 9
    },
    {
        number: 28,
        symbol: "Ni",
        name: "Níquel",
        mass: "58.693",
        category: "transition-metal",
        config: "[Ar] 3d⁸ 4s²",
        state: "Sólido",
        density: "8.912 g/cm³",
        melting: "1455°C",
        boiling: "2913°C",
        row: 4,
        col: 10
    },
    {
        number: 29,
        symbol: "Cu",
        name: "Cobre",
        mass: "63.546",
        category: "transition-metal",
        config: "[Ar] 3d¹⁰ 4s¹",
        state: "Sólido",
        density: "8.96 g/cm³",
        melting: "1084.62°C",
        boiling: "2562°C",
        row: 4,
        col: 11
    },
    {
        number: 30,
        symbol: "Zn",
        name: "Zinco",
        mass: "65.38",
        category: "transition-metal",
        config: "[Ar] 3d¹⁰ 4s²",
        state: "Sólido",
        density: "7.134 g/cm³",
        melting: "419.53°C",
        boiling: "907°C",
        row: 4,
        col: 12
    },
    {
        number: 31,
        symbol: "Ga",
        name: "Gálio",
        mass: "69.723",
        category: "post-transition-metal",
        config: "[Ar] 3d¹⁰ 4s² 4p¹",
        state: "Sólido",
        density: "5.907 g/cm³",
        melting: "29.76°C",
        boiling: "2204°C",
        row: 4,
        col: 13
    },
    {
        number: 32,
        symbol: "Ge",
        name: "Germânio",
        mass: "72.64",
        category: "metalloid",
        config: "[Ar] 3d¹⁰ 4s² 4p²",
        state: "Sólido",
        density: "5.323 g/cm³",
        melting: "938.25°C",
        boiling: "2833°C",
        row: 4,
        col: 14
    },
    {
        number: 33,
        symbol: "As",
        name: "Arsênio",
        mass: "74.922",
        category: "metalloid",
        config: "[Ar] 3d¹⁰ 4s² 4p³",
        state: "Sólido",
        density: "5.776 g/cm³",
        melting: "817°C",
        boiling: "614°C",
        row: 4,
        col: 15
    },
    {
        number: 34,
        symbol: "Se",
        name: "Selênio",
        mass: "78.96",
        category: "nonmetal",
        config: "[Ar] 3d¹⁰ 4s² 4p⁴",
        state: "Sólido",
        density: "4.809 g/cm³",
        melting: "221°C",
        boiling: "685°C",
        row: 4,
        col: 16
    },
    {
        number: 35,
        symbol: "Br",
        name: "Bromo",
        mass: "79.904",
        category: "halogen",
        config: "[Ar] 3d¹⁰ 4s² 4p⁵",
        state: "Líquido",
        density: "3.122 g/cm³",
        melting: "-7.35°C",
        boiling: "58.8°C",
        row: 4,
        col: 17
    },
    {
        number: 36,
        symbol: "Kr",
        name: "Criptônio",
        mass: "83.798",
        category: "noble-gas",
        config: "[Ar] 3d¹⁰ 4s² 4p⁶",
        state: "Gás",
        density: "3.733 g/L",
        melting: "-157.36°C",
        boiling: "-153.22°C",
        row: 4,
        col: 18
    },
    {
        number: 37,
        symbol: "Rb",
        name: "Rubídio",
        mass: "85.468",
        category: "alkali-metal",
        config: "[Kr] 5s¹",
        state: "Sólido",
        density: "1.532 g/cm³",
        melting: "39.31°C",
        boiling: "688°C",
        row: 5,
        col: 1
    },
    {
        number: 38,
        symbol: "Sr",
        name: "Estrôncio",
        mass: "87.62",
        category: "alkaline-earth-metal",
        config: "[Kr] 5s²",
        state: "Sólido",
        density: "2.64 g/cm³",
        melting: "777°C",
        boiling: "1382°C",
        row: 5,
        col: 2
    },
    {
        number: 39,
        symbol: "Y",
        name: "Ítrio",
        mass: "88.906",
        category: "transition-metal",
        config: "[Kr] 4d¹ 5s²",
        state: "Sólido",
        density: "4.469 g/cm³",
        melting: "1526°C",
        boiling: "3345°C",
        row: 5,
        col: 3
    },
    {
        number: 40,
        symbol: "Zr",
        name: "Zircônio",
        mass: "91.224",
        category: "transition-metal",
        config: "[Kr] 4d² 5s²",
        state: "Sólido",
        density: "6.506 g/cm³",
        melting: "1855°C",
        boiling: "4409°C",
        row: 5,
        col: 4
    },
    {
        number: 41,
        symbol: "Nb",
        name: "Nióbio",
        mass: "92.906",
        category: "transition-metal",
        config: "[Kr] 4d⁴ 5s¹",
        state: "Sólido",
        density: "8.57 g/cm³",
        melting: "2477°C",
        boiling: "4744°C",
        row: 5,
        col: 5
    },
    {
        number: 42,
        symbol: "Mo",
        name: "Molibdênio",
        mass: "95.96",
        category: "transition-metal",
        config: "[Kr] 4d⁵ 5s¹",
        state: "Sólido",
        density: "10.22 g/cm³",
        melting: "2623°C",
        boiling: "4639°C",
        row: 5,
        col: 6
    },
    {
        number: 43,
        symbol: "Tc",
        name: "Tecnécio",
        mass: "98",
        category: "transition-metal",
        config: "[Kr] 4d⁵ 5s²",
        state: "Sólido",
        density: "11.5 g/cm³",
        melting: "2157°C",
        boiling: "4265°C",
        row: 5,
        col: 7
    },
    {
        number: 44,
        symbol: "Ru",
        name: "Rutênio",
        mass: "101.07",
        category: "transition-metal",
        config: "[Kr] 4d⁷ 5s¹",
        state: "Sólido",
        density: "12.37 g/cm³",
        melting: "2334°C",
        boiling: "4150°C",
        row: 5,
        col: 8
    },
    {
        number: 45,
        symbol: "Rh",
        name: "Ródio",
        mass: "102.91",
        category: "transition-metal",
        config: "[Kr] 4d⁸ 5s¹",
        state: "Sólido",
        density: "12.41 g/cm³",
        melting: "1964°C",
        boiling: "3695°C",
        row: 5,
        col: 9
    },
    {
        number: 46,
        symbol: "Pd",
        name: "Paládio",
        mass: "106.42",
        category: "transition-metal",
        config: "[Kr] 4d¹⁰",
        state: "Sólido",
        density: "12.02 g/cm³",
        melting: "1554.9°C",
        boiling: "2963°C",
        row: 5,
        col: 10
    },
    {
        number: 47,
        symbol: "Ag",
        name: "Prata",
        mass: "107.87",
        category: "transition-metal",
        config: "[Kr] 4d¹⁰ 5s¹",
        state: "Sólido",
        density: "10.501 g/cm³",
        melting: "961.78°C",
        boiling: "2162°C",
        row: 5,
        col: 11
    },
    {
        number: 48,
        symbol: "Cd",
        name: "Cádmio",
        mass: "112.41",
        category: "transition-metal",
        config: "[Kr] 4d¹⁰ 5s²",
        state: "Sólido",
        density: "8.69 g/cm³",
        melting: "321.07°C",
        boiling: "767°C",
        row: 5,
        col: 12
    },
    {
        number: 49,
        symbol: "In",
        name: "Índio",
        mass: "114.82",
        category: "post-transition-metal",
        config: "[Kr] 4d¹⁰ 5s² 5p¹",
        state: "Sólido",
        density: "7.31 g/cm³",
        melting: "156.6°C",
        boiling: "2072°C",
        row: 5,
        col: 13
    },
    {
        number: 50,
        symbol: "Sn",
        name: "Estanho",
        mass: "118.71",
        category: "post-transition-metal",
        config: "[Kr] 4d¹⁰ 5s² 5p²",
        state: "Sólido",
        density: "7.287 g/cm³",
        melting: "231.93°C",
        boiling: "2602°C",
        row: 5,
        col: 14
    },
    {
        number: 51,
        symbol: "Sb",
        name: "Antimônio",
        mass: "121.76",
        category: "metalloid",
        config: "[Kr] 4d¹⁰ 5s² 5p³",
        state: "Sólido",
        density: "6.685 g/cm³",
        melting: "630.63°C",
        boiling: "1587°C",
        row: 5,
        col: 15
    },
    {
        number: 52,
        symbol: "Te",
        name: "Telúrio",
        mass: "127.6",
        category: "metalloid",
        config: "[Kr] 4d¹⁰ 5s² 5p⁴",
        state: "Sólido",
        density: "6.232 g/cm³",
        melting: "449.51°C",
        boiling: "988°C",
        row: 5,
        col: 16
    },
    {
        number: 53,
        symbol: "I",
        name: "Iodo",
        mass: "126.90",
        category: "halogen",
        config: "[Kr] 4d¹⁰ 5s² 5p⁵",
        state: "Sólido",
        density: "4.93 g/cm³",
        melting: "113.7°C",
        boiling: "184.3°C",
        row: 5,
        col: 17
    },
    {
        number: 54,
        symbol: "Xe",
        name: "Xenônio",
        mass: "131.29",
        category: "noble-gas",
        config: "[Kr] 4d¹⁰ 5s² 5p⁶",
        state: "Gás",
        density: "5.887 g/L",
        melting: "-111.75°C",
        boiling: "-108.09°C",
        row: 5,
        col: 18
    },
    {
        number: 55,
        symbol: "Cs",
        name: "Césio",
        mass: "132.91",
        category: "alkali-metal",
        config: "[Xe] 6s¹",
        state: "Sólido",
        density: "1.873 g/cm³",
        melting: "28.44°C",
        boiling: "671°C",
        row: 6,
        col: 1
    },
    {
        number: 56,
        symbol: "Ba",
        name: "Bário",
        mass: "137.33",
        category: "alkaline-earth-metal",
        config: "[Xe] 6s²",
        state: "Sólido",
        density: "3.594 g/cm³",
        melting: "727°C",
        boiling: "1897°C",
        row: 6,
        col: 2
    },
    {
        number: 57,
        symbol: "La",
        name: "Lantânio",
        mass: "138.91",
        category: "lanthanide",
        config: "[Xe] 5d¹ 6s²",
        state: "Sólido",
        density: "6.145 g/cm³",
        melting: "920°C",
        boiling: "3464°C",
        row: 8,
        col: 3
    },
    {
        number: 58,
        symbol: "Ce",
        name: "Cério",
        mass: "140.12",
        category: "lanthanide",
        config: "[Xe] 4f¹ 5d¹ 6s²",
        state: "Sólido",
        density: "6.77 g/cm³",
        melting: "795°C",
        boiling: "3443°C",
        row: 8,
        col: 4
    },
    {
        number: 59,
        symbol: "Pr",
        name: "Praseodímio",
        mass: "140.91",
        category: "lanthanide",
        config: "[Xe] 4f³ 6s²",
        state: "Sólido",
        density: "6.773 g/cm³",
        melting: "931°C",
        boiling: "3520°C",
        row: 8,
        col: 5
    },
    {
        number: 60,
        symbol: "Nd",
        name: "Neodímio",
        mass: "144.24",
        category: "lanthanide",
        config: "[Xe] 4f⁴ 6s²",
        state: "Sólido",
        density: "7.007 g/cm³",
        melting: "1021°C",
        boiling: "3074°C",
        row: 8,
        col: 6
    },
    {
        number: 61,
        symbol: "Pm",
        name: "Promécio",
        mass: "145",
        category: "lanthanide",
        config: "[Xe] 4f⁵ 6s²",
        state: "Sólido",
        density: "7.26 g/cm³",
        melting: "1042°C",
        boiling: "3000°C",
        row: 8,
        col: 7
    },
    {
        number: 62,
        symbol: "Sm",
        name: "Samário",
        mass: "150.36",
        category: "lanthanide",
        config: "[Xe] 4f⁶ 6s²",
        state: "Sólido",
        density: "7.52 g/cm³",
        melting: "1074°C",
        boiling: "1794°C",
        row: 8,
        col: 8
    },
    {
        number: 63,
        symbol: "Eu",
        name: "Európio",
        mass: "151.96",
        category: "lanthanide",
        config: "[Xe] 4f⁷ 6s²",
        state: "Sólido",
        density: "5.243 g/cm³",
        melting: "822°C",
        boiling: "1529°C",
        row: 8,
        col: 9
    },
    {
        number: 64,
        symbol: "Gd",
        name: "Gadolínio",
        mass: "157.25",
        category: "lanthanide",
        config: "[Xe] 4f⁷ 5d¹ 6s²",
        state: "Sólido",
        density: "7.895 g/cm³",
        melting: "1313°C",
        boiling: "3273°C",
        row: 8,
        col: 10
    },
    {
        number: 65,
        symbol: "Tb",
        name: "Térbio",
        mass: "158.93",
        category: "lanthanide",
        config: "[Xe] 4f⁹ 6s²",
        state: "Sólido",
        density: "8.229 g/cm³",
        melting: "1356°C",
        boiling: "3230°C",
        row: 8,
        col: 11
    },
    {
        number: 66,
        symbol: "Dy",
        name: "Disprósio",
        mass: "162.50",
        category: "lanthanide",
        config: "[Xe] 4f¹⁰ 6s²",
        state: "Sólido",
        density: "8.55 g/cm³",
        melting: "1412°C",
        boiling: "2567°C",
        row: 8,
        col: 12
    },
    {
        number: 67,
        symbol: "Ho",
        name: "Hólmio",
        mass: "164.93",
        category: "lanthanide",
        config: "[Xe] 4f¹¹ 6s²",
        state: "Sólido",
        density: "8.795 g/cm³",
        melting: "1474°C",
        boiling: "2700°C",
        row: 8,
        col: 13
    },
    {
        number: 68,
        symbol: "Er",
        name: "Érbio",
        mass: "167.26",
        category: "lanthanide",
        config: "[Xe] 4f¹² 6s²",
        state: "Sólido",
        density: "9.066 g/cm³",
        melting: "1529°C",
        boiling: "2868°C",
        row: 8,
        col: 14
    },
    {
        number: 69,
        symbol: "Tm",
        name: "Túlio",
        mass: "168.93",
        category: "lanthanide",
        config: "[Xe] 4f¹³ 6s²",
        state: "Sólido",
        density: "9.321 g/cm³",
        melting: "1545°C",
        boiling: "1950°C",
        row: 8,
        col: 15
    },
    {
        number: 70,
        symbol: "Yb",
        name: "Itérbio",
        mass: "173.05",
        category: "lanthanide",
        config: "[Xe] 4f¹⁴ 6s²",
        state: "Sólido",
        density: "6.965 g/cm³",
        melting: "819°C",
        boiling: "1196°C",
        row: 8,
        col: 16
    },
    {
        number: 71,
        symbol: "Lu",
        name: "Lutécio",
        mass: "174.97",
        category: "lanthanide",
        config: "[Xe] 4f¹⁴ 5d¹ 6s²",
        state: "Sólido",
        density: "9.84 g/cm³",
        melting: "1663°C",
        boiling: "3402°C",
        row: 8,
        col: 17
    },
    {
        number: 72,
        symbol: "Hf",
        name: "Háfnio",
        mass: "178.49",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d² 6s²",
        state: "Sólido",
        density: "13.31 g/cm³",
        melting: "2233°C",
        boiling: "4603°C",
        row: 6,
        col: 4
    },
    {
        number: 73,
        symbol: "Ta",
        name: "Tântalo",
        mass: "180.95",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d³ 6s²",
        state: "Sólido",
        density: "16.654 g/cm³",
        melting: "3017°C",
        boiling: "5458°C",
        row: 6,
        col: 5
    },
    {
        number: 74,
        symbol: "W",
        name: "Tungstênio",
        mass: "183.84",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁴ 6s²",
        state: "Sólido",
        density: "19.25 g/cm³",
        melting: "3414°C",
        boiling: "5555°C",
        row: 6,
        col: 6
    },
    {
        number: 75,
        symbol: "Re",
        name: "Rênio",
        mass: "186.21",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁵ 6s²",
        state: "Sólido",
        density: "21.02 g/cm³",
        melting: "3186°C",
        boiling: "5596°C",
        row: 6,
        col: 7
    },
    {
        number: 76,
        symbol: "Os",
        name: "Ósmio",
        mass: "190.23",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁶ 6s²",
        state: "Sólido",
        density: "22.61 g/cm³",
        melting: "3033°C",
        boiling: "5012°C",
        row: 6,
        col: 8
    },
    {
        number: 77,
        symbol: "Ir",
        name: "Irídio",
        mass: "192.22",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁷ 6s²",
        state: "Sólido",
        density: "22.56 g/cm³",
        melting: "2466°C",
        boiling: "4428°C",
        row: 6,
        col: 9
    },
    {
        number: 78,
        symbol: "Pt",
        name: "Platina",
        mass: "195.08",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
        state: "Sólido",
        density: "21.46 g/cm³",
        melting: "1768.3°C",
        boiling: "3825°C",
        row: 6,
        col: 10
    },
    {
        number: 79,
        symbol: "Au",
        name: "Ouro",
        mass: "196.97",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
        state: "Sólido",
        density: "19.282 g/cm³",
        melting: "1064.18°C",
        boiling: "2856°C",
        row: 6,
        col: 11
    },
    {
        number: 80,
        symbol: "Hg",
        name: "Mercúrio",
        mass: "200.59",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
        state: "Líquido",
        density: "13.5336 g/cm³",
        melting: "-38.83°C",
        boiling: "356.73°C",
        row: 6,
        col: 12
    },
    {
        number: 81,
        symbol: "Tl",
        name: "Tálio",
        mass: "204.38",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
        state: "Sólido",
        density: "11.85 g/cm³",
        melting: "304°C",
        boiling: "1473°C",
        row: 6,
        col: 13
    },
    {
        number: 82,
        symbol: "Pb",
        name: "Chumbo",
        mass: "207.2",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
        state: "Sólido",
        density: "11.342 g/cm³",
        melting: "327.46°C",
        boiling: "1749°C",
        row: 6,
        col: 14
    },
    {
        number: 83,
        symbol: "Bi",
        name: "Bismuto",
        mass: "208.98",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
        state: "Sólido",
        density: "9.807 g/cm³",
        melting: "271.4°C",
        boiling: "1564°C",
        row: 6,
        col: 15
    },
    {
        number: 84,
        symbol: "Po",
        name: "Polônio",
        mass: "209",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
        state: "Sólido",
        density: "9.32 g/cm³",
        melting: "254°C",
        boiling: "962°C",
        row: 6,
        col: 16
    },
    {
        number: 85,
        symbol: "At",
        name: "Astato",
        mass: "210",
        category: "halogen",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
        state: "Sólido",
        density: "7 g/cm³",
        melting: "302°C",
        boiling: "337°C",
        row: 6,
        col: 17
    },
    {
        number: 86,
        symbol: "Rn",
        name: "Radônio",
        mass: "222",
        category: "noble-gas",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
        state: "Gás",
        density: "9.73 g/L",
        melting: "-71°C",
        boiling: "-62°C",
        row: 6,
        col: 18
    },
    {
        number: 87,
        symbol: "Fr",
        name: "Frâncio",
        mass: "223",
        category: "alkali-metal",
        config: "[Rn] 7s¹",
        state: "Sólido",
        density: "1.87 g/cm³",
        melting: "27°C",
        boiling: "677°C",
        row: 7,
        col: 1
    },
    {
        number: 88,
        symbol: "Ra",
        name: "Rádio",
        mass: "226",
        category: "alkaline-earth-metal",
        config: "[Rn] 7s²",
        state: "Sólido",
        density: "5.5 g/cm³",
        melting: "696°C",
        boiling: "1737°C",
        row: 7,
        col: 2
    },
    {
        number: 89,
        symbol: "Ac",
        name: "Actínio",
        mass: "227",
        category: "actinide",
        config: "[Rn] 6d¹ 7s²",
        state: "Sólido",
        density: "10.07 g/cm³",
        melting: "1051°C",
        boiling: "3198°C",
        row: 9,
        col: 3
    },
    {
        number: 90,
        symbol: "Th",
        name: "Tório",
        mass: "232.04",
        category: "actinide",
        config: "[Rn] 6d² 7s²",
        state: "Sólido",
        density: "11.72 g/cm³",
        melting: "1750°C",
        boiling: "4788°C",
        row: 9,
        col: 4
    },
    {
        number: 91,
        symbol: "Pa",
        name: "Protactínio",
        mass: "231.04",
        category: "actinide",
        config: "[Rn] 5f² 6d¹ 7s²",
        state: "Sólido",
        density: "15.37 g/cm³",
        melting: "1572°C",
        boiling: "4000°C",
        row: 9,
        col: 5
    },
    {
        number: 92,
        symbol: "U",
        name: "Urânio",
        mass: "238.03",
        category: "actinide",
        config: "[Rn] 5f³ 6d¹ 7s²",
        state: "Sólido",
        density: "18.95 g/cm³",
        melting: "1135°C",
        boiling: "4131°C",
        row: 9,
        col: 6
    },
    {
        number: 93,
        symbol: "Np",
        name: "Netúnio",
        mass: "237",
        category: "actinide",
        config: "[Rn] 5f⁴ 6d¹ 7s²",
        state: "Sólido",
        density: "20.25 g/cm³",
        melting: "644°C",
        boiling: "4000°C",
        row: 9,
        col: 7
    },
    {
        number: 94,
        symbol: "Pu",
        name: "Plutônio",
        mass: "244",
        category: "actinide",
        config: "[Rn] 5f⁶ 7s²",
        state: "Sólido",
        density: "19.84 g/cm³",
        melting: "640°C",
        boiling: "3228°C",
        row: 9,
        col: 8
    },
    {
        number: 95,
        symbol: "Am",
        name: "Amerício",
        mass: "243",
        category: "actinide",
        config: "[Rn] 5f⁷ 7s²",
        state: "Sólido",
        density: "13.69 g/cm³",
        melting: "1176°C",
        boiling: "2607°C",
        row: 9,
        col: 9
    },
    {
        number: 96,
        symbol: "Cm",
        name: "Cúrio",
        mass: "247",
        category: "actinide",
        config: "[Rn] 5f⁷ 6d¹ 7s²",
        state: "Sólido",
        density: "13.51 g/cm³",
        melting: "1345°C",
        boiling: "3110°C",
        row: 9,
        col: 10
    },
    {
        number: 97,
        symbol: "Bk",
        name: "Berquélio",
        mass: "247",
        category: "actinide",
        config: "[Rn] 5f⁹ 7s²",
        state: "Sólido",
        density: "14.79 g/cm³",
        melting: "1050°C",
        boiling: "2627°C",
        row: 9,
        col: 11
    },
    {
        number: 98,
        symbol: "Cf",
        name: "Califórnio",
        mass: "251",
        category: "actinide",
        config: "[Rn] 5f¹⁰ 7s²",
        state: "Sólido",
        density: "15.1 g/cm³",
        melting: "900°C",
        boiling: "1743°C",
        row: 9,
        col: 12
    },
    {
        number: 99,
        symbol: "Es",
        name: "Einstênio",
        mass: "252",
        category: "actinide",
        config: "[Rn] 5f¹¹ 7s²",
        state: "Sólido",
        density: "8.84 g/cm³",
        melting: "860°C",
        boiling: "1130°C",
        row: 9,
        col: 13
    },
    {
        number: 100,
        symbol: "Fm",
        name: "Férmio",
        mass: "257",
        category: "actinide",
        config: "[Rn] 5f¹² 7s²",
        state: "Sólido",
        density: "9.7 g/cm³",
        melting: "1527°C",
        boiling: "N/A",
        row: 9,
        col: 14
    },
    {
        number: 101,
        symbol: "Md",
        name: "Mendelévio",
        mass: "258",
        category: "actinide",
        config: "[Rn] 5f¹³ 7s²",
        state: "Sólido",
        density: "10.3 g/cm³",
        melting: "827°C",
        boiling: "N/A",
        row: 9,
        col: 15
    },
    {
        number: 102,
        symbol: "No",
        name: "Nobélio",
        mass: "259",
        category: "actinide",
        config: "[Rn] 5f¹⁴ 7s²",
        state: "Sólido",
        density: "9.9 g/cm³",
        melting: "827°C",
        boiling: "N/A",
        row: 9,
        col: 16
    },
    {
        number: 103,
        symbol: "Lr",
        name: "Laurêncio",
        mass: "262",
        category: "actinide",
        config: "[Rn] 5f¹⁴ 7s² 7p¹",
        state: "Sólido",
        density: "15.6 g/cm³",
        melting: "1627°C",
        boiling: "N/A",
        row: 9,
        col: 17
    },
    {
        number: 104,
        symbol: "Rf",
        name: "Rutherfórdio",
        mass: "267",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d² 7s²",
        state: "Sólido",
        density: "23 g/cm³",
        melting: "2100°C",
        boiling: "5500°C",
        row: 7,
        col: 4
    },
    {
        number: 105,
        symbol: "Db",
        name: "Dúbnio",
        mass: "268",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d³ 7s²",
        state: "Sólido",
        density: "29 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 5
    },
    {
        number: 106,
        symbol: "Sg",
        name: "Seabórgio",
        mass: "269",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁴ 7s²",
        state: "Sólido",
        density: "35 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 6
    },
    {
        number: 107,
        symbol: "Bh",
        name: "Bóhrio",
        mass: "270",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁵ 7s²",
        state: "Sólido",
        density: "37 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 7
    },
    {
        number: 108,
        symbol: "Hs",
        name: "Hássio",
        mass: "277",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁶ 7s²",
        state: "Sólido",
        density: "40 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 8
    },
    {
        number: 109,
        symbol: "Mt",
        name: "Meitnério",
        mass: "278",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁷ 7s²",
        state: "Sólido",
        density: "37 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 9
    },
    {
        number: 110,
        symbol: "Ds",
        name: "Darmstádtio",
        mass: "281",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁸ 7s²",
        state: "Sólido",
        density: "34 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 10
    },
    {
        number: 111,
        symbol: "Rg",
        name: "Roentgênio",
        mass: "282",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁹ 7s²",
        state: "Sólido",
        density: "28 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 11
    },
    {
        number: 112,
        symbol: "Cn",
        name: "Copernício",
        mass: "285",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
        state: "Sólido",
        density: "23 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 12
    },
    {
        number: 113,
        symbol: "Nh",
        name: "Nihônio",
        mass: "286",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
        state: "Sólido",
        density: "16 g/cm³",
        melting: "700°C",
        boiling: "1400°C",
        row: 7,
        col: 13
    },
    {
        number: 114,
        symbol: "Fl",
        name: "Fleróvio",
        mass: "289",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
        state: "Sólido",
        density: "14 g/cm³",
        melting: "200°C",
        boiling: "380°C",
        row: 7,
        col: 14
    },
    {
        number: 115,
        symbol: "Mc",
        name: "Moscóvio",
        mass: "290",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
        state: "Sólido",
        density: "13.5 g/cm³",
        melting: "700°C",
        boiling: "1400°C",
        row: 7,
        col: 15
    },
    {
        number: 116,
        symbol: "Lv",
        name: "Livermório",
        mass: "293",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
        state: "Sólido",
        density: "12.9 g/cm³",
        melting: "708°C",
        boiling: "1085°C",
        row: 7,
        col: 16
    },
    {
        number: 117,
        symbol: "Ts",
        name: "Tenesso",
        mass: "294",
        category: "halogen",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
        state: "Sólido",
        density: "7.2 g/cm³",
        melting: "723°C",
        boiling: "883°C",
        row: 7,
        col: 17
    },
    {
        number: 118,
        symbol: "Og",
        name: "Oganessônio",
        mass: "294",
        category: "noble-gas",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
        state: "Gás",
        density: "4.95 g/L",
        melting: "52°C",
        boiling: "177°C",
        row: 7,
        col: 18
    }
];

// Mapeamento de categorias para nomes em português
const categoryNames = {
    'alkali-metal': 'Metal Alcalino',
    'alkaline-earth-metal': 'Metal Alcalino-terroso',
    'transition-metal': 'Metal de Transição',
    'post-transition-metal': 'Metal Pós-transição',
    'metalloid': 'Metaloide',
    'nonmetal': 'Não Metal',
    'halogen': 'Halogênio',
    'noble-gas': 'Gás Nobre',
    'lanthanide': 'Lantanídeo',
    'actinide': 'Actinídeo'
};
