// Dados completos dos elementos químicos da tabela periódica
const elementsData = [
    {
        number: 1,
        symbol: "H",
        name: "Hidrogênio",
        mass: "1.008",
        category: "nonmetal",
        config: "1s¹",
        state: "Gás",
        density: "0.08988 g/L",
        melting: "-259.14°C",
        boiling: "-252.87°C",
        row: 1,
        col: 1,
        nox: ["-1", "+1"],
        commonNox: "+1",
        atomicRadius: "37 pm",
        electronegativity: "2.20",
        ionizationEnergy: "1312 kJ/mol",
        abundance: "0.14%",
        discoveryYear: "1766",
        applications: "Combustível, fertilizantes, produção de amônia, hidrogenação",
        noxExplanation: "O hidrogênio pode perder seu único elétron formando H⁺ ou ganhar um elétron formando H⁻ (em hidretos metálicos)."
    },
    {
        number: 2,
        symbol: "He",
        name: "Hélio",
        mass: "4.003",
        category: "noble-gas",
        config: "1s²",
        state: "Gás",
        density: "0.1786 g/L",
        melting: "-272.2°C",
        boiling: "-268.93°C",
        row: 1,
        col: 18,
        nox: ["0"],
        commonNox: "0",
        atomicRadius: "31 pm",
        electronegativity: "N/A",
        ionizationEnergy: "2372 kJ/mol",
        abundance: "0.000005%",
        discoveryYear: "1895",
        applications: "Balões, refrigeração criogênica, atmosfera inerte para soldagem",
        noxExplanation: "O hélio é um gás nobre com configuração eletrônica estável, não forma compostos químicos comuns."
    },
    {
        number: 3,
        symbol: "Li",
        name: "Lítio",
        mass: "6.941",
        category: "alkali-metal",
        config: "[He] 2s¹",
        state: "Sólido",
        density: "0.534 g/cm³",
        melting: "180.5°C",
        boiling: "1342°C",
        row: 2,
        col: 1,
        nox: ["+1"],
        atomicRadius: "152 pm",
        electronegativity: "0.98",
        ionizationEnergy: "520 kJ/mol",
        abundance: "0.002%",
        discoveryYear: "1817",
        applications: "Baterias, ligas metálicas, medicamentos psiquiátricos",
        commonNox: "+1",
        noxExplanation: "O lítio perde facilmente seu elétron de valência, formando o íon Li⁺."
    },
    {
        number: 4,
        symbol: "Be",
        name: "Berílio",
        mass: "9.012",
        category: "alkaline-earth-metal",
        config: "[He] 2s²",
        state: "Sólido",
        density: "1.85 g/cm³",
        melting: "1287°C",
        boiling: "2469°C",
        row: 2,
        col: 2,
        nox: ["+2"],
        commonNox: "+2",
        atomicRadius: "112 pm",
        electronegativity: "1.57",
        ionizationEnergy: "899 kJ/mol",
        abundance: "0.0002%",
        discoveryYear: "1798",
        applications: "Ligas aeroespaciais, janelas de raios-X, moderador de nêutrons",
        noxExplanation: "O berílio perde seus dois elétrons de valência, formando o íon Be²⁺."
    },
    {
        number: 5,
        symbol: "B",
        name: "Boro",
        mass: "10.811",
        category: "metalloid",
        config: "[He] 2s² 2p¹",
        state: "Sólido",
        density: "2.34 g/cm³",
        melting: "2075°C",
        boiling: "4000°C",
        row: 2,
        col: 13,
        nox: ["-3", "+3"],
        commonNox: "+3",
        atomicRadius: "87 pm",
        electronegativity: "2.04",
        ionizationEnergy: "801 kJ/mol",
        abundance: "0.001%",
        discoveryYear: "1808",
        applications: "Vidros borossilicatos, cerâmicas, detergentes, semicondutores",
        noxExplanation: "O boro pode formar compostos covalentes perdendo 3 elétrons ou compartilhando-os."
    },
    {
        number: 6,
        symbol: "C",
        name: "Carbono",
        mass: "12.011",
        category: "nonmetal",
        config: "[He] 2s² 2p²",
        state: "Sólido",
        density: "2.267 g/cm³",
        melting: "3550°C",
        boiling: "4027°C",
        row: 2,
        col: 14,
        nox: ["-4", "-3", "-2", "-1", "0", "+1", "+2", "+3", "+4"],
        commonNox: "+4",
        atomicRadius: "67 pm",
        electronegativity: "2.55",
        ionizationEnergy: "1086 kJ/mol",
        abundance: "0.02%",
        discoveryYear: "Pré-histórico",
        applications: "Compostos orgânicos, diamante, grafite, nanotubos de carbono",
        noxExplanation: "O carbono apresenta grande versatilidade, podendo formar 4 ligações covalentes."
    },
    {
        number: 7,
        symbol: "N",
        name: "Nitrogênio",
        mass: "14.007",
        category: "nonmetal",
        config: "[He] 2s² 2p³",
        state: "Gás",
        density: "1.251 g/L",
        melting: "-210.1°C",
        boiling: "-195.79°C",
        row: 2,
        col: 15,
        nox: ["-3", "-2", "-1", "0", "+1", "+2", "+3", "+4", "+5"],
        commonNox: "-3",
        atomicRadius: "56 pm",
        electronegativity: "3.04",
        ionizationEnergy: "1402 kJ/mol",
        abundance: "0.002%",
        discoveryYear: "1772",
        applications: "Fertilizantes, explosivos, atmosfera inerte, produção de amônia",
        noxExplanation: "O nitrogênio tende a completar seu octeto ganhando 3 elétrons, mas pode apresentar vários NOX."
    },
    {
        number: 8,
        symbol: "O",
        name: "Oxigênio",
        mass: "15.999",
        category: "nonmetal",
        config: "[He] 2s² 2p⁴",
        state: "Gás",
        density: "1.429 g/L",
        melting: "-218.79°C",
        boiling: "-182.95°C",
        row: 2,
        col: 16,
        nox: ["-2", "-1", "0", "+1", "+2"],
        commonNox: "-2",
        noxExplanation: "O oxigênio tende a ganhar 2 elétrons completando seu octeto, exceto em peróxidos (-1)."
    },
    {
        number: 9,
        symbol: "F",
        name: "Flúor",
        mass: "18.998",
        category: "halogen",
        config: "[He] 2s² 2p⁵",
        state: "Gás",
        density: "1.696 g/L",
        melting: "-219.67°C",
        boiling: "-188.11°C",
        row: 2,
        col: 17,
        nox: ["-1", "0"],
        commonNox: "-1",
        atomicRadius: "42 pm",
        electronegativity: "3.98",
        ionizationEnergy: "1681 kJ/mol",
        abundance: "0.065%",
        discoveryYear: "1886",
        applications: "Pasta de dente, refrigerantes, teflon, enriquecimento de urânio",
        noxExplanation: "O flúor é o mais eletronegativo, sempre -1 em compostos (exceto F₂)."
    },
    {
        number: 10,
        symbol: "Ne",
        name: "Neônio",
        mass: "20.180",
        category: "noble-gas",
        config: "[He] 2s² 2p⁶",
        state: "Gás",
        density: "0.9 g/L",
        melting: "-248.59°C",
        boiling: "-246.05°C",
        row: 2,
        col: 18,
        nox: ["0"],
        commonNox: "0",
        atomicRadius: "38 pm",
        electronegativity: "N/A",
        ionizationEnergy: "2081 kJ/mol",
        abundance: "0.000005%",
        discoveryYear: "1898",
        applications: "Letreiros luminosos, lasers, refrigeração criogênica",
        noxExplanation: "O neônio é um gás nobre, não forma compostos químicos comuns."
    },
    {
        number: 11,
        symbol: "Na",
        name: "Sódio",
        mass: "22.990",
        category: "alkali-metal",
        config: "[Ne] 3s¹",
        state: "Sólido",
        density: "0.971 g/cm³",
        melting: "97.79°C",
        boiling: "883°C",
        row: 3,
        col: 1,
        nox: ["+1"],
        commonNox: "+1",
        atomicRadius: "186 pm",
        electronegativity: "0.93",
        ionizationEnergy: "496 kJ/mol",
        abundance: "2.36%",
        discoveryYear: "1807",
        applications: "Sal de cozinha, sabão, lâmpadas de vapor de sódio",
        noxExplanation: "O sódio perde facilmente seu elétron de valência, formando Na⁺."
    },
    {
        number: 12,
        symbol: "Mg",
        name: "Magnésio",
        mass: "24.305",
        category: "alkaline-earth-metal",
        config: "[Ne] 3s²",
        state: "Sólido",
        density: "1.738 g/cm³",
        melting: "650°C",
        boiling: "1090°C",
        row: 3,
        col: 2,
        nox: ["+2"],
        commonNox: "+2",
        atomicRadius: "160 pm",
        electronegativity: "1.31",
        ionizationEnergy: "738 kJ/mol",
        abundance: "2.33%",
        discoveryYear: "1808",
        applications: "Ligas leves, fogos de artifício, suplementos nutricionais",
        noxExplanation: "O magnésio perde seus dois elétrons de valência, formando Mg²⁺."
    },
    {
        number: 13,
        symbol: "Al",
        name: "Alumínio",
        mass: "26.982",
        category: "post-transition-metal",
        config: "[Ne] 3s² 3p¹",
        state: "Sólido",
        density: "2.698 g/cm³",
        melting: "660.32°C",
        boiling: "2519°C",
        row: 3,
        col: 13,
        nox: ["+3"],
        commonNox: "+3",
        atomicRadius: "118 pm",
        electronegativity: "1.61",
        ionizationEnergy: "578 kJ/mol",
        abundance: "8.23%",
        discoveryYear: "1825",
        applications: "Latas, aviões, construção civil, cabos elétricos",
        noxExplanation: "O alumínio perde seus três elétrons de valência, formando Al³⁺."
    },
    {
        number: 14,
        symbol: "Si",
        name: "Silício",
        mass: "28.086",
        category: "metalloid",
        config: "[Ne] 3s² 3p²",
        state: "Sólido",
        density: "2.329 g/cm³",
        melting: "1414°C",
        boiling: "3265°C",
        row: 3,
        col: 14,
        nox: ["-4", "+2", "+4"],
        commonNox: "+4",
        atomicRadius: "111 pm",
        electronegativity: "1.90",
        ionizationEnergy: "787 kJ/mol",
        abundance: "27.7%",
        discoveryYear: "1854",
        applications: "Semicondutores, chips de computador, vidro, cimento",
        noxExplanation: "O silício forma principalmente compostos covalentes, especialmente SiO₄⁴⁻."
    },
    {
        number: 15,
        symbol: "P",
        name: "Fósforo",
        mass: "30.974",
        category: "nonmetal",
        config: "[Ne] 3s² 3p³",
        state: "Sólido",
        density: "1.82 g/cm³",
        melting: "44.15°C",
        boiling: "280.5°C",
        row: 3,
        col: 15,
        nox: ["-3", "+1", "+3", "+5"],
        commonNox: "+5",
        atomicRadius: "98 pm",
        electronegativity: "2.19",
        ionizationEnergy: "1012 kJ/mol",
        abundance: "0.105%",
        discoveryYear: "1669",
        applications: "Fertilizantes, detergentes, fósforos, DNA/RNA",
        noxExplanation: "O fósforo pode ganhar 3 elétrons ou usar diferentes orbitais d para oxidações positivas."
    },
    {
        number: 16,
        symbol: "S",
        name: "Enxofre",
        mass: "32.065",
        category: "nonmetal",
        config: "[Ne] 3s² 3p⁴",
        state: "Sólido",
        density: "2.067 g/cm³",
        melting: "115.21°C",
        boiling: "444.61°C",
        row: 3,
        col: 16,
        nox: ["-2", "+2", "+4", "+6"],
        commonNox: "-2",
        atomicRadius: "88 pm",
        electronegativity: "2.58",
        ionizationEnergy: "1000 kJ/mol",
        abundance: "0.035%",
        discoveryYear: "Pré-histórico",
        applications: "Ácido sulfúrico, pólvora, vulcanização da borracha",
        noxExplanation: "O enxofre tende a ganhar 2 elétrons, mas pode usar orbitais d para NOX positivos."
    },
    {
        number: 17,
        symbol: "Cl",
        name: "Cloro",
        mass: "35.453",
        category: "halogen",
        config: "[Ne] 3s² 3p⁵",
        state: "Gás",
        density: "3.214 g/L",
        melting: "-101.5°C",
        boiling: "-34.04°C",
        row: 3,
        col: 17,
        nox: ["-1", "+1", "+3", "+5", "+7"],
        commonNox: "-1",
        atomicRadius: "79 pm",
        electronegativity: "3.16",
        ionizationEnergy: "1251 kJ/mol",
        abundance: "0.015%",
        discoveryYear: "1774",
        applications: "Desinfetante, PVC, água tratada, alvejante",
        noxExplanation: "O cloro tende a ganhar 1 elétron, mas pode usar orbitais d para NOX positivos."
    },
    {
        number: 18,
        symbol: "Ar",
        name: "Argônio",
        mass: "39.948",
        category: "noble-gas",
        config: "[Ne] 3s² 3p⁶",
        state: "Gás",
        density: "1.784 g/L",
        melting: "-189.35°C",
        boiling: "-185.85°C",
        row: 3,
        col: 18,
        nox: ["0"],
        commonNox: "0",
        atomicRadius: "71 pm",
        electronegativity: "N/A",
        ionizationEnergy: "1521 kJ/mol",
        abundance: "0.00015%",
        discoveryYear: "1894",
        applications: "Soldagem, lâmpadas incandescentes, atmosfera inerte",
        noxExplanation: "O argônio é um gás nobre, não forma compostos químicos comuns."
    },
    {
        number: 19,
        symbol: "K",
        name: "Potássio",
        mass: "39.098",
        category: "alkali-metal",
        config: "[Ar] 4s¹",
        state: "Sólido",
        density: "0.862 g/cm³",
        melting: "63.5°C",
        boiling: "759°C",
        row: 4,
        col: 1,
        nox: ["+1"],
        commonNox: "+1",
        atomicRadius: "203 pm",
        electronegativity: "0.82",
        ionizationEnergy: "419 kJ/mol",
        abundance: "2.09%",
        discoveryYear: "1807",
        applications: "Fertilizantes, sabão, vidro, explosivos",
        noxExplanation: "O potássio perde facilmente seu elétron de valência, formando K⁺."
    },
    {
        number: 20,
        symbol: "Ca",
        name: "Cálcio",
        mass: "40.078",
        category: "alkaline-earth-metal",
        config: "[Ar] 4s²",
        state: "Sólido",
        density: "1.54 g/cm³",
        melting: "842°C",
        boiling: "1484°C",
        row: 4,
        col: 2,
        nox: ["+2"],
        commonNox: "+2",
        atomicRadius: "176 pm",
        electronegativity: "1.00",
        ionizationEnergy: "590 kJ/mol",
        abundance: "4.15%",
        discoveryYear: "1808",
        applications: "Cimento, gesso, ossos e dentes, suplementos",
        noxExplanation: "O cálcio perde seus dois elétrons de valência, formando Ca²⁺."
    },
    {
        number: 21,
        symbol: "Sc",
        name: "Escândio",
        mass: "44.956",
        category: "transition-metal",
        config: "[Ar] 3d¹ 4s²",
        state: "Sólido",
        density: "2.989 g/cm³",
        melting: "1541°C",
        boiling: "2836°C",
        row: 4,
        col: 3,
        nox: ["+3"],
        commonNox: "+3",
        atomicRadius: "170 pm",
        electronegativity: "1.36",
        ionizationEnergy: "633 kJ/mol",
        abundance: "0.0022%",
        discoveryYear: "1879",
        applications: "Ligas aeroespaciais, lâmpadas de alta intensidade",
        noxExplanation: "O escândio forma principalmente o íon Sc³⁺."
    },
    {
        number: 22,
        symbol: "Ti",
        name: "Titânio",
        mass: "47.867",
        category: "transition-metal",
        config: "[Ar] 3d² 4s²",
        state: "Sólido",
        density: "4.506 g/cm³",
        melting: "1668°C",
        boiling: "3287°C",
        row: 4,
        col: 4,
        nox: ["+2", "+3", "+4"],
        commonNox: "+4",
        atomicRadius: "160 pm",
        electronegativity: "1.54",
        ionizationEnergy: "659 kJ/mol",
        abundance: "0.565%",
        discoveryYear: "1791",
        applications: "Implantes médicos, aviação, tinta branca, joias",
        noxExplanation: "O titânio apresenta múltiplos estados de oxidação, sendo +4 o mais estável."
    },
    {
        number: 23,
        symbol: "V",
        name: "Vanádio",
        mass: "50.942",
        category: "transition-metal",
        config: "[Ar] 3d³ 4s²",
        state: "Sólido",
        density: "6.11 g/cm³",
        melting: "1910°C",
        boiling: "3407°C",
        row: 4,
        col: 5,
        nox: ["+2", "+3", "+4", "+5"],
        commonNox: "+5",
        atomicRadius: "153 pm",
        electronegativity: "1.63",
        ionizationEnergy: "651 kJ/mol",
        abundance: "0.012%",
        discoveryYear: "1801",
        applications: "Ligas de aço, catalisadores, baterias redox",
        noxExplanation: "O vanádio apresenta vários NOX, sendo +5 comum em vanadatos."
    },
    {
        number: 24,
        symbol: "Cr",
        name: "Cromo",
        mass: "51.996",
        category: "transition-metal",
        config: "[Ar] 3d⁵ 4s¹",
        state: "Sólido",
        density: "7.15 g/cm³",
        melting: "1907°C",
        boiling: "2671°C",
        row: 4,
        col: 6,
        nox: ["+2", "+3", "+6"],
        commonNox: "+3",
        atomicRadius: "139 pm",
        electronegativity: "1.66",
        ionizationEnergy: "653 kJ/mol",
        abundance: "0.010%",
        discoveryYear: "1797",
        applications: "Aço inoxidável, cromagem, pigmentos, curtimento",
        noxExplanation: "O cromo apresenta NOX +3 (estável) e +6 (em dicromatos)."
    },
    {
        number: 25,
        symbol: "Mn",
        name: "Manganês",
        mass: "54.938",
        category: "transition-metal",
        config: "[Ar] 3d⁵ 4s²",
        state: "Sólido",
        density: "7.44 g/cm³",
        melting: "1246°C",
        boiling: "2061°C",
        row: 4,
        col: 7,
        nox: ["+2", "+3", "+4", "+6", "+7"],
        commonNox: "+2",
        atomicRadius: "139 pm",
        electronegativity: "1.55",
        ionizationEnergy: "717 kJ/mol",
        abundance: "0.095%",
        discoveryYear: "1774",
        applications: "Ligas de aço, baterias, fertilizantes, permanganato",
        noxExplanation: "O manganês apresenta grande variedade de NOX, +7 em permanganatos."
    },
    {
        number: 26,
        symbol: "Fe",
        name: "Ferro",
        mass: "55.845",
        category: "transition-metal",
        config: "[Ar] 3d⁶ 4s²",
        state: "Sólido",
        density: "7.874 g/cm³",
        melting: "1538°C",
        boiling: "2861°C",
        row: 4,
        col: 8,
        nox: ["+2", "+3"],
        commonNox: "+3",
        atomicRadius: "132 pm",
        electronegativity: "1.83",
        ionizationEnergy: "762 kJ/mol",
        abundance: "5.63%",
        discoveryYear: "Pré-histórico",
        applications: "Aço, construção, transporte, hemoglobina",
        noxExplanation: "O ferro apresenta principalmente NOX +2 e +3, sendo +3 mais estável."
    },
    {
        number: 27,
        symbol: "Co",
        name: "Cobalto",
        mass: "58.933",
        category: "transition-metal",
        config: "[Ar] 3d⁷ 4s²",
        state: "Sólido",
        density: "8.86 g/cm³",
        melting: "1495°C",
        boiling: "2927°C",
        row: 4,
        col: 9,
        nox: ["+2", "+3"],
        commonNox: "+2",
        atomicRadius: "126 pm",
        electronegativity: "1.88",
        ionizationEnergy: "760 kJ/mol",
        abundance: "0.0025%",
        discoveryYear: "1735",
        applications: "Ímãs, baterias de lítio, catalisadores, pigmento azul",
        noxExplanation: "O cobalto apresenta NOX +2 (mais comum) e +3."
    },
    {
        number: 28,
        symbol: "Ni",
        name: "Níquel",
        mass: "58.693",
        category: "transition-metal",
        config: "[Ar] 3d⁸ 4s²",
        state: "Sólido",
        density: "8.912 g/cm³",
        melting: "1455°C",
        boiling: "2913°C",
        row: 4,
        col: 10,
        nox: ["+2", "+3"],
        commonNox: "+2",
        atomicRadius: "124 pm",
        electronegativity: "1.91",
        ionizationEnergy: "737 kJ/mol",
        abundance: "0.0084%",
        discoveryYear: "1751",
        applications: "Moedas, aço inoxidável, baterias, catalisadores",
        noxExplanation: "O níquel apresenta principalmente NOX +2, menos comum +3."
    },
    {
        number: 29,
        symbol: "Cu",
        name: "Cobre",
        mass: "63.546",
        category: "transition-metal",
        config: "[Ar] 3d¹⁰ 4s¹",
        state: "Sólido",
        density: "8.96 g/cm³",
        melting: "1084.62°C",
        boiling: "2562°C",
        row: 4,
        col: 11,
        nox: ["+1", "+2"],
        commonNox: "+2",
        atomicRadius: "128 pm",
        electronegativity: "1.90",
        ionizationEnergy: "745 kJ/mol",
        abundance: "0.006%",
        discoveryYear: "Pré-histórico",
        applications: "Fiação elétrica, encanamento, moedas, ligas",
        noxExplanation: "O cobre apresenta NOX +1 (cuproso) e +2 (cúprico)."
    },
    {
        number: 30,
        symbol: "Zn",
        name: "Zinco",
        mass: "65.38",
        category: "transition-metal",
        config: "[Ar] 3d¹⁰ 4s²",
        state: "Sólido",
        density: "7.134 g/cm³",
        melting: "419.53°C",
        boiling: "907°C",
        row: 4,
        col: 12,
        nox: ["+2"],
        commonNox: "+2",
        atomicRadius: "134 pm",
        electronegativity: "1.65",
        ionizationEnergy: "906 kJ/mol",
        abundance: "0.007%",
        discoveryYear: "1746",
        applications: "Galvanização, baterias, ligas (latão), suplementos",
        noxExplanation: "O zinco perde seus dois elétrons 4s, formando Zn²⁺."
    },
    {
        number: 31,
        symbol: "Ga",
        name: "Gálio",
        mass: "69.723",
        category: "post-transition-metal",
        config: "[Ar] 3d¹⁰ 4s² 4p¹",
        state: "Sólido",
        density: "5.907 g/cm³",
        melting: "29.76°C",
        boiling: "2204°C",
        row: 4,
        col: 13,
        nox: ["+3"],
        commonNox: "+3",
        atomicRadius: "136 pm",
        electronegativity: "1.81",
        ionizationEnergy: "579 kJ/mol",
        abundance: "0.0019%",
        discoveryYear: "1875",
        applications: "Semicondutores, LEDs, termômetros, ligas de baixo ponto de fusão",
        noxExplanation: "O gálio perde seus três elétrons de valência, formando Ga³⁺."
    },
    {
        number: 32,
        symbol: "Ge",
        name: "Germânio",
        mass: "72.64",
        category: "metalloid",
        config: "[Ar] 3d¹⁰ 4s² 4p²",
        state: "Sólido",
        density: "5.323 g/cm³",
        melting: "938.25°C",
        boiling: "2833°C",
        row: 4,
        col: 14,
        nox: ["-4", "+2", "+4"],
        commonNox: "+4",
        atomicRadius: "125 pm",
        electronegativity: "2.01",
        ionizationEnergy: "762 kJ/mol",
        abundance: "0.00015%",
        discoveryYear: "1886",
        applications: "Semicondutores, transistores, fibra óptica, catalisadores",
        noxExplanation: "O germânio apresenta NOX +4 mais comum, similar ao silício."
    },
    {
        number: 33,
        symbol: "As",
        name: "Arsênio",
        mass: "74.922",
        category: "metalloid",
        config: "[Ar] 3d¹⁰ 4s² 4p³",
        state: "Sólido",
        density: "5.776 g/cm³",
        melting: "817°C",
        boiling: "614°C",
        row: 4,
        col: 15,
        nox: ["-3", "+3", "+5"],
        commonNox: "+3",
        atomicRadius: "114 pm",
        electronegativity: "2.18",
        ionizationEnergy: "947 kJ/mol",
        abundance: "0.00015%",
        discoveryYear: "1250",
        applications: "Semicondutores, pesticidas, preservativos de madeira, ligas",
        noxExplanation: "O arsênio pode ganhar 3 elétrons ou apresentar NOX positivos."
    },
    {
        number: 34,
        symbol: "Se",
        name: "Selênio",
        mass: "78.96",
        category: "nonmetal",
        config: "[Ar] 3d¹⁰ 4s² 4p⁴",
        state: "Sólido",
        density: "4.809 g/cm³",
        melting: "221°C",
        boiling: "685°C",
        row: 4,
        col: 16,
        nox: ["-2", "+2", "+4", "+6"],
        commonNox: "-2",
        atomicRadius: "103 pm",
        electronegativity: "2.55",
        ionizationEnergy: "941 kJ/mol",
        abundance: "0.00005%",
        discoveryYear: "1817",
        applications: "Células solares, fotocopiadoras, suplementos nutricionais, vidro",
        noxExplanation: "O selênio comporta-se similarmente ao enxofre."
    },
    {
        number: 35,
        symbol: "Br",
        name: "Bromo",
        mass: "79.904",
        category: "halogen",
        config: "[Ar] 3d¹⁰ 4s² 4p⁵",
        state: "Líquido",
        density: "3.122 g/cm³",
        melting: "-7.35°C",
        boiling: "58.8°C",
        row: 4,
        col: 17,
        nox: ["-1", "+1", "+3", "+5", "+7"],
        commonNox: "-1",
        atomicRadius: "94 pm",
        electronegativity: "2.96",
        ionizationEnergy: "1140 kJ/mol",
        abundance: "0.0003%",
        discoveryYear: "1826",
        applications: "Desinfetantes, retardantes de chama, fotografia, medicamentos",
        noxExplanation: "O bromo comporta-se similarmente ao cloro."
    },
    {
        number: 36,
        symbol: "Kr",
        name: "Criptônio",
        mass: "83.798",
        category: "noble-gas",
        config: "[Ar] 3d¹⁰ 4s² 4p⁶",
        state: "Gás",
        density: "3.733 g/L",
        melting: "-157.36°C",
        boiling: "-153.22°C",
        row: 4,
        col: 18,
        nox: ["0", "+2"],
        commonNox: "0",
        atomicRadius: "88 pm",
        electronegativity: "3.00",
        ionizationEnergy: "1351 kJ/mol",
        abundance: "0.000001%",
        discoveryYear: "1898",
        applications: "Lâmpadas de alta intensidade, lasers, atmosfera inerte",
        noxExplanation: "O criptônio raramente forma compostos, exceto alguns com flúor."
    },
    {
        number: 37,
        symbol: "Rb",
        name: "Rubídio",
        mass: "85.468",
        category: "alkali-metal",
        config: "[Kr] 5s¹",
        state: "Sólido",
        density: "1.532 g/cm³",
        melting: "39.31°C",
        boiling: "688°C",
        row: 5,
        col: 1,
        nox: ["+1"],
        commonNox: "+1",
        atomicRadius: "248 pm",
        electronegativity: "0.82",
        ionizationEnergy: "403 kJ/mol",
        abundance: "0.009%",
        discoveryYear: "1861",
        applications: "Fotocélulas, catalisadores, pesquisa científica",
        noxExplanation: "O rubídio perde facilmente seu elétron de valência."
    },
    {
        number: 38,
        symbol: "Sr",
        name: "Estrôncio",
        mass: "87.62",
        category: "alkaline-earth-metal",
        config: "[Kr] 5s²",
        state: "Sólido",
        density: "2.64 g/cm³",
        melting: "777°C",
        boiling: "1382°C",
        row: 5,
        col: 2,
        nox: ["+2"],
        commonNox: "+2",
        atomicRadius: "215 pm",
        electronegativity: "0.95",
        ionizationEnergy: "550 kJ/mol",
        abundance: "0.037%",
        discoveryYear: "1790",
        applications: "Fogos de artifício, imãs permanentes, tratamento de osteoporose",
        noxExplanation: "O estrôncio perde seus dois elétrons de valência."
    },
    {
        number: 39,
        symbol: "Y",
        name: "Ítrio",
        mass: "88.906",
        category: "transition-metal",
        config: "[Kr] 4d¹ 5s²",
        state: "Sólido",
        density: "4.469 g/cm³",
        melting: "1526°C",
        boiling: "3345°C",
        row: 5,
        col: 3,
        nox: ["+3"],
        commonNox: "+3",
        atomicRadius: "180 pm",
        electronegativity: "1.22",
        ionizationEnergy: "600 kJ/mol",
        abundance: "0.0033%",
        discoveryYear: "1794",
        applications: "Supercondutores, LEDs, lasers, ligas de alumínio",
        noxExplanation: "O ítrio forma principalmente o íon Y³⁺."
    },
    {
        number: 40,
        symbol: "Zr",
        name: "Zircônio",
        mass: "91.224",
        category: "transition-metal",
        config: "[Kr] 4d² 5s²",
        state: "Sólido",
        density: "6.506 g/cm³",
        melting: "1855°C",
        boiling: "4409°C",
        row: 5,
        col: 4,
        nox: ["+4"],
        commonNox: "+4",
        atomicRadius: "160 pm",
        electronegativity: "1.33",
        ionizationEnergy: "640 kJ/mol",
        abundance: "0.0165%",
        discoveryYear: "1789",
        applications: "Reatores nucleares, cerâmicas, joias, implantes médicos",
        noxExplanation: "O zircônio apresenta principalmente NOX +4."
    },
    {
        number: 41,
        symbol: "Nb",
        name: "Nióbio",
        mass: "92.906",
        category: "transition-metal",
        config: "[Kr] 4d⁴ 5s¹",
        state: "Sólido",
        density: "8.57 g/cm³",
        melting: "2477°C",
        boiling: "4744°C",
        row: 5,
        col: 5,
        nox: ["+3", "+5"],
        commonNox: "+5",
        atomicRadius: "146 pm",
        electronegativity: "1.6",
        ionizationEnergy: "652 kJ/mol",
        abundance: "0.002%",
        discoveryYear: "1801",
        applications: "Supercondutores, aços especiais, joias, catalisadores",
        noxExplanation: "O nióbio apresenta principalmente NOX +5."
    },
    {
        number: 42,
        symbol: "Mo",
        name: "Molibdênio",
        mass: "95.96",
        category: "transition-metal",
        config: "[Kr] 4d⁵ 5s¹",
        state: "Sólido",
        density: "10.22 g/cm³",
        melting: "2623°C",
        boiling: "4639°C",
        row: 5,
        col: 6,
        nox: ["+2", "+3", "+4", "+5", "+6"],
        commonNox: "+6",
        atomicRadius: "139 pm",
        electronegativity: "2.16",
        ionizationEnergy: "684 kJ/mol",
        abundance: "0.0015%",
        discoveryYear: "1781",
        applications: "Aços especiais, catalisadores, lubrificantes, fertilizantes",
        noxExplanation: "O molibdênio apresenta vários NOX, sendo +6 o mais comum."
    },
    {
        number: 43,
        symbol: "Tc",
        name: "Tecnécio",
        mass: "98",
        category: "transition-metal",
        config: "[Kr] 4d⁵ 5s²",
        state: "Sólido",
        density: "11.5 g/cm³",
        melting: "2157°C",
        boiling: "4265°C",
        row: 5,
        col: 7
    },
    {
        number: 44,
        symbol: "Ru",
        name: "Rutênio",
        mass: "101.07",
        category: "transition-metal",
        config: "[Kr] 4d⁷ 5s¹",
        state: "Sólido",
        density: "12.37 g/cm³",
        melting: "2334°C",
        boiling: "4150°C",
        row: 5,
        col: 8
    },
    {
        number: 45,
        symbol: "Rh",
        name: "Ródio",
        mass: "102.91",
        category: "transition-metal",
        config: "[Kr] 4d⁸ 5s¹",
        state: "Sólido",
        density: "12.41 g/cm³",
        melting: "1964°C",
        boiling: "3695°C",
        row: 5,
        col: 9
    },
    {
        number: 46,
        symbol: "Pd",
        name: "Paládio",
        mass: "106.42",
        category: "transition-metal",
        config: "[Kr] 4d¹⁰",
        state: "Sólido",
        density: "12.02 g/cm³",
        melting: "1554.9°C",
        boiling: "2963°C",
        row: 5,
        col: 10
    },
    {
        number: 47,
        symbol: "Ag",
        name: "Prata",
        mass: "107.87",
        category: "transition-metal",
        config: "[Kr] 4d¹⁰ 5s¹",
        state: "Sólido",
        density: "10.501 g/cm³",
        melting: "961.78°C",
        boiling: "2162°C",
        row: 5,
        col: 11,
        nox: ["+1", "+2"],
        commonNox: "+1",
        atomicRadius: "144 pm",
        electronegativity: "1.93",
        ionizationEnergy: "731 kJ/mol",
        abundance: "0.00008%",
        discoveryYear: "Pré-histórico",
        applications: "Joias, moedas, eletrônicos, fotografia, medicina",
        noxExplanation: "A prata apresenta principalmente NOX +1."
    },
    {
        number: 48,
        symbol: "Cd",
        name: "Cádmio",
        mass: "112.41",
        category: "transition-metal",
        config: "[Kr] 4d¹⁰ 5s²",
        state: "Sólido",
        density: "8.69 g/cm³",
        melting: "321.07°C",
        boiling: "767°C",
        row: 5,
        col: 12,
        nox: ["+2"],
        commonNox: "+2",
        atomicRadius: "151 pm",
        electronegativity: "1.69",
        ionizationEnergy: "868 kJ/mol",
        abundance: "0.000015%",
        discoveryYear: "1817",
        applications: "Baterias, pigmentos, galvanização, semicondutores",
        noxExplanation: "O cádmio perde seus dois elétrons 5s."
    },
    {
        number: 49,
        symbol: "In",
        name: "Índio",
        mass: "114.82",
        category: "post-transition-metal",
        config: "[Kr] 4d¹⁰ 5s² 5p¹",
        state: "Sólido",
        density: "7.31 g/cm³",
        melting: "156.6°C",
        boiling: "2072°C",
        row: 5,
        col: 13,
        nox: ["+1", "+3"],
        commonNox: "+3",
        atomicRadius: "167 pm",
        electronegativity: "1.78",
        ionizationEnergy: "558 kJ/mol",
        abundance: "0.000025%",
        discoveryYear: "1863",
        applications: "Telas de toque, LEDs, painéis solares, soldas",
        noxExplanation: "O índio apresenta principalmente NOX +3."
    },
    {
        number: 50,
        symbol: "Sn",
        name: "Estanho",
        mass: "118.71",
        category: "post-transition-metal",
        config: "[Kr] 4d¹⁰ 5s² 5p²",
        state: "Sólido",
        density: "7.287 g/cm³",
        melting: "231.93°C",
        boiling: "2602°C",
        row: 5,
        col: 14,
        nox: ["+2", "+4"],
        commonNox: "+4",
        atomicRadius: "145 pm",
        electronegativity: "1.96",
        ionizationEnergy: "709 kJ/mol",
        abundance: "0.00023%",
        discoveryYear: "Pré-histórico",
        applications: "Latas, soldas, bronze, vidro, conservação de alimentos",
        noxExplanation: "O estanho apresenta NOX +2 (estanoso) e +4 (estânico)."
    },
    {
        number: 51,
        symbol: "Sb",
        name: "Antimônio",
        mass: "121.76",
        category: "metalloid",
        config: "[Kr] 4d¹⁰ 5s² 5p³",
        state: "Sólido",
        density: "6.685 g/cm³",
        melting: "630.63°C",
        boiling: "1587°C",
        row: 5,
        col: 15,
        nox: ["-3", "+3", "+5"],
        commonNox: "+3",
        atomicRadius: "133 pm",
        electronegativity: "2.05",
        ionizationEnergy: "834 kJ/mol",
        abundance: "0.00002%",
        discoveryYear: "Pré-histórico",
        applications: "Baterias, semicondutores, retardantes de chama, ligas",
        noxExplanation: "O antimônio pode ganhar 3 elétrons ou apresentar NOX positivos."
    },
    {
        number: 52,
        symbol: "Te",
        name: "Telúrio",
        mass: "127.6",
        category: "metalloid",
        config: "[Kr] 4d¹⁰ 5s² 5p⁴",
        state: "Sólido",
        density: "6.232 g/cm³",
        melting: "449.51°C",
        boiling: "988°C",
        row: 5,
        col: 16,
        nox: ["-2", "+2", "+4", "+6"],
        commonNox: "+4",
        atomicRadius: "123 pm",
        electronegativity: "2.1",
        ionizationEnergy: "869 kJ/mol",
        abundance: "0.000001%",
        discoveryYear: "1782",
        applications: "Semicondutores, ligas, catalisadores, painéis solares",
        noxExplanation: "O telúrio apresenta principalmente NOX +4."
    },
    {
        number: 53,
        symbol: "I",
        name: "Iodo",
        mass: "126.90",
        category: "halogen",
        config: "[Kr] 4d¹⁰ 5s² 5p⁵",
        state: "Sólido",
        density: "4.93 g/cm³",
        melting: "113.7°C",
        boiling: "184.3°C",
        row: 5,
        col: 17,
        nox: ["-1", "+1", "+3", "+5", "+7"],
        commonNox: "-1",
        atomicRadius: "115 pm",
        electronegativity: "2.66",
        ionizationEnergy: "1008 kJ/mol",
        abundance: "0.00045%",
        discoveryYear: "1811",
        applications: "Desinfetantes, medicamentos, fotografia, sal iodado",
        noxExplanation: "O iodo comporta-se como os outros halogênios."
    },
    {
        number: 54,
        symbol: "Xe",
        name: "Xenônio",
        mass: "131.29",
        category: "noble-gas",
        config: "[Kr] 4d¹⁰ 5s² 5p⁶",
        state: "Gás",
        density: "5.887 g/L",
        melting: "-111.75°C",
        boiling: "-108.09°C",
        row: 5,
        col: 18,
        nox: ["0", "+2", "+4", "+6"],
        commonNox: "0",
        atomicRadius: "108 pm",
        electronegativity: "2.6",
        ionizationEnergy: "1170 kJ/mol",
        abundance: "0.0000036%",
        discoveryYear: "1898",
        applications: "Lâmpadas de alta intensidade, anestésicos, propulsão espacial",
        noxExplanation: "O xenônio pode formar alguns compostos, especialmente com flúor."
    },
    {
        number: 55,
        symbol: "Cs",
        name: "Césio",
        mass: "132.91",
        category: "alkali-metal",
        config: "[Xe] 6s¹",
        state: "Sólido",
        density: "1.873 g/cm³",
        melting: "28.44°C",
        boiling: "671°C",
        row: 6,
        col: 1,
        nox: ["+1"],
        commonNox: "+1",
        atomicRadius: "265 pm",
        electronegativity: "0.79",
        ionizationEnergy: "376 kJ/mol",
        abundance: "0.0003%",
        discoveryYear: "1860",
        applications: "Relógios atômicos, catalisadores, células fotovoltaicas",
        noxExplanation: "O césio perde facilmente seu elétron de valência."
    },
    {
        number: 56,
        symbol: "Ba",
        name: "Bário",
        mass: "137.33",
        category: "alkaline-earth-metal",
        config: "[Xe] 6s²",
        state: "Sólido",
        density: "3.594 g/cm³",
        melting: "727°C",
        boiling: "1897°C",
        row: 6,
        col: 2,
        nox: ["+2"],
        commonNox: "+2",
        atomicRadius: "217 pm",
        electronegativity: "0.89",
        ionizationEnergy: "503 kJ/mol",
        abundance: "0.0425%",
        discoveryYear: "1808",
        applications: "Contraste para raios-X, fogos de artifício, vidros especiais",
        noxExplanation: "O bário perde seus dois elétrons de valência."
    },
    {
        number: 57,
        symbol: "La",
        name: "Lantânio",
        mass: "138.91",
        category: "lanthanide",
        config: "[Xe] 5d¹ 6s²",
        state: "Sólido",
        density: "6.145 g/cm³",
        melting: "920°C",
        boiling: "3464°C",
        row: 8,
        col: 3,
        nox: ["+3"],
        commonNox: "+3",
        atomicRadius: "195 pm",
        electronegativity: "1.10",
        ionizationEnergy: "538 kJ/mol",
        abundance: "0.0034%",
        discoveryYear: "1839",
        applications: "Catalisadores, lentes ópticas, baterias recarregáveis",
        noxExplanation: "O lantânio forma principalmente o íon La³⁺."
    },
    {
        number: 58,
        symbol: "Ce",
        name: "Cério",
        mass: "140.12",
        category: "lanthanide",
        config: "[Xe] 4f¹ 5d¹ 6s²",
        state: "Sólido",
        density: "6.77 g/cm³",
        melting: "795°C",
        boiling: "3443°C",
        row: 8,
        col: 4
    },
    {
        number: 59,
        symbol: "Pr",
        name: "Praseodímio",
        mass: "140.91",
        category: "lanthanide",
        config: "[Xe] 4f³ 6s²",
        state: "Sólido",
        density: "6.773 g/cm³",
        melting: "931°C",
        boiling: "3520°C",
        row: 8,
        col: 5
    },
    {
        number: 60,
        symbol: "Nd",
        name: "Neodímio",
        mass: "144.24",
        category: "lanthanide",
        config: "[Xe] 4f⁴ 6s²",
        state: "Sólido",
        density: "7.007 g/cm³",
        melting: "1021°C",
        boiling: "3074°C",
        row: 8,
        col: 6
    },
    {
        number: 61,
        symbol: "Pm",
        name: "Promécio",
        mass: "145",
        category: "lanthanide",
        config: "[Xe] 4f⁵ 6s²",
        state: "Sólido",
        density: "7.26 g/cm³",
        melting: "1042°C",
        boiling: "3000°C",
        row: 8,
        col: 7
    },
    {
        number: 62,
        symbol: "Sm",
        name: "Samário",
        mass: "150.36",
        category: "lanthanide",
        config: "[Xe] 4f⁶ 6s²",
        state: "Sólido",
        density: "7.52 g/cm³",
        melting: "1074°C",
        boiling: "1794°C",
        row: 8,
        col: 8
    },
    {
        number: 63,
        symbol: "Eu",
        name: "Európio",
        mass: "151.96",
        category: "lanthanide",
        config: "[Xe] 4f⁷ 6s²",
        state: "Sólido",
        density: "5.243 g/cm³",
        melting: "822°C",
        boiling: "1529°C",
        row: 8,
        col: 9
    },
    {
        number: 64,
        symbol: "Gd",
        name: "Gadolínio",
        mass: "157.25",
        category: "lanthanide",
        config: "[Xe] 4f⁷ 5d¹ 6s²",
        state: "Sólido",
        density: "7.895 g/cm³",
        melting: "1313°C",
        boiling: "3273°C",
        row: 8,
        col: 10
    },
    {
        number: 65,
        symbol: "Tb",
        name: "Térbio",
        mass: "158.93",
        category: "lanthanide",
        config: "[Xe] 4f⁹ 6s²",
        state: "Sólido",
        density: "8.229 g/cm³",
        melting: "1356°C",
        boiling: "3230°C",
        row: 8,
        col: 11
    },
    {
        number: 66,
        symbol: "Dy",
        name: "Disprósio",
        mass: "162.50",
        category: "lanthanide",
        config: "[Xe] 4f¹⁰ 6s²",
        state: "Sólido",
        density: "8.55 g/cm³",
        melting: "1412°C",
        boiling: "2567°C",
        row: 8,
        col: 12
    },
    {
        number: 67,
        symbol: "Ho",
        name: "Hólmio",
        mass: "164.93",
        category: "lanthanide",
        config: "[Xe] 4f¹¹ 6s²",
        state: "Sólido",
        density: "8.795 g/cm³",
        melting: "1474°C",
        boiling: "2700°C",
        row: 8,
        col: 13
    },
    {
        number: 68,
        symbol: "Er",
        name: "Érbio",
        mass: "167.26",
        category: "lanthanide",
        config: "[Xe] 4f¹² 6s²",
        state: "Sólido",
        density: "9.066 g/cm³",
        melting: "1529°C",
        boiling: "2868°C",
        row: 8,
        col: 14
    },
    {
        number: 69,
        symbol: "Tm",
        name: "Túlio",
        mass: "168.93",
        category: "lanthanide",
        config: "[Xe] 4f¹³ 6s²",
        state: "Sólido",
        density: "9.321 g/cm³",
        melting: "1545°C",
        boiling: "1950°C",
        row: 8,
        col: 15
    },
    {
        number: 70,
        symbol: "Yb",
        name: "Itérbio",
        mass: "173.05",
        category: "lanthanide",
        config: "[Xe] 4f¹⁴ 6s²",
        state: "Sólido",
        density: "6.965 g/cm³",
        melting: "819°C",
        boiling: "1196°C",
        row: 8,
        col: 16
    },
    {
        number: 71,
        symbol: "Lu",
        name: "Lutécio",
        mass: "174.97",
        category: "lanthanide",
        config: "[Xe] 4f¹⁴ 5d¹ 6s²",
        state: "Sólido",
        density: "9.84 g/cm³",
        melting: "1663°C",
        boiling: "3402°C",
        row: 8,
        col: 17
    },
    {
        number: 72,
        symbol: "Hf",
        name: "Háfnio",
        mass: "178.49",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d² 6s²",
        state: "Sólido",
        density: "13.31 g/cm³",
        melting: "2233°C",
        boiling: "4603°C",
        row: 6,
        col: 4
    },
    {
        number: 73,
        symbol: "Ta",
        name: "Tântalo",
        mass: "180.95",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d³ 6s²",
        state: "Sólido",
        density: "16.654 g/cm³",
        melting: "3017°C",
        boiling: "5458°C",
        row: 6,
        col: 5
    },
    {
        number: 74,
        symbol: "W",
        name: "Tungstênio",
        mass: "183.84",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁴ 6s²",
        state: "Sólido",
        density: "19.25 g/cm³",
        melting: "3414°C",
        boiling: "5555°C",
        row: 6,
        col: 6
    },
    {
        number: 75,
        symbol: "Re",
        name: "Rênio",
        mass: "186.21",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁵ 6s²",
        state: "Sólido",
        density: "21.02 g/cm³",
        melting: "3186°C",
        boiling: "5596°C",
        row: 6,
        col: 7
    },
    {
        number: 76,
        symbol: "Os",
        name: "Ósmio",
        mass: "190.23",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁶ 6s²",
        state: "Sólido",
        density: "22.61 g/cm³",
        melting: "3033°C",
        boiling: "5012°C",
        row: 6,
        col: 8
    },
    {
        number: 77,
        symbol: "Ir",
        name: "Irídio",
        mass: "192.22",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁷ 6s²",
        state: "Sólido",
        density: "22.56 g/cm³",
        melting: "2466°C",
        boiling: "4428°C",
        row: 6,
        col: 9
    },
    {
        number: 78,
        symbol: "Pt",
        name: "Platina",
        mass: "195.08",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
        state: "Sólido",
        density: "21.46 g/cm³",
        melting: "1768.3°C",
        boiling: "3825°C",
        row: 6,
        col: 10
    },
    {
        number: 79,
        symbol: "Au",
        name: "Ouro",
        mass: "196.97",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
        state: "Sólido",
        density: "19.282 g/cm³",
        melting: "1064.18°C",
        boiling: "2856°C",
        row: 6,
        col: 11,
        nox: ["+1", "+3"],
        commonNox: "+3",
        atomicRadius: "144 pm",
        electronegativity: "2.54",
        ionizationEnergy: "890 kJ/mol",
        abundance: "0.000004%",
        discoveryYear: "Pré-histórico",
        applications: "Joias, eletrônicos, medicina, catalisadores, reserva de valor",
        noxExplanation: "O ouro apresenta NOX +1 (auroso) e +3 (áurico)."
    },
    {
        number: 80,
        symbol: "Hg",
        name: "Mercúrio",
        mass: "200.59",
        category: "transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
        state: "Líquido",
        density: "13.5336 g/cm³",
        melting: "-38.83°C",
        boiling: "356.73°C",
        row: 6,
        col: 12,
        nox: ["+1", "+2"],
        commonNox: "+2",
        atomicRadius: "151 pm",
        electronegativity: "2.00",
        ionizationEnergy: "1007 kJ/mol",
        abundance: "0.000085%",
        discoveryYear: "Pré-histórico",
        applications: "Termômetros, lâmpadas, amálgamas dentárias, catalisadores",
        noxExplanation: "O mercúrio apresenta NOX +1 (mercuroso) e +2 (mercúrico)."
    },
    {
        number: 81,
        symbol: "Tl",
        name: "Tálio",
        mass: "204.38",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
        state: "Sólido",
        density: "11.85 g/cm³",
        melting: "304°C",
        boiling: "1473°C",
        row: 6,
        col: 13
    },
    {
        number: 82,
        symbol: "Pb",
        name: "Chumbo",
        mass: "207.2",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
        state: "Sólido",
        density: "11.342 g/cm³",
        melting: "327.46°C",
        boiling: "1749°C",
        row: 6,
        col: 14,
        nox: ["+2", "+4"],
        commonNox: "+2",
        atomicRadius: "175 pm",
        electronegativity: "2.33",
        ionizationEnergy: "716 kJ/mol",
        abundance: "0.0014%",
        discoveryYear: "Pré-histórico",
        applications: "Baterias, construção, munição, proteção contra radiação",
        noxExplanation: "O chumbo apresenta NOX +2 (plumboso) e +4 (plúmbico)."
    },
    {
        number: 83,
        symbol: "Bi",
        name: "Bismuto",
        mass: "208.98",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
        state: "Sólido",
        density: "9.807 g/cm³",
        melting: "271.4°C",
        boiling: "1564°C",
        row: 6,
        col: 15
    },
    {
        number: 84,
        symbol: "Po",
        name: "Polônio",
        mass: "209",
        category: "post-transition-metal",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
        state: "Sólido",
        density: "9.32 g/cm³",
        melting: "254°C",
        boiling: "962°C",
        row: 6,
        col: 16
    },
    {
        number: 85,
        symbol: "At",
        name: "Astato",
        mass: "210",
        category: "halogen",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
        state: "Sólido",
        density: "7 g/cm³",
        melting: "302°C",
        boiling: "337°C",
        row: 6,
        col: 17
    },
    {
        number: 86,
        symbol: "Rn",
        name: "Radônio",
        mass: "222",
        category: "noble-gas",
        config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
        state: "Gás",
        density: "9.73 g/L",
        melting: "-71°C",
        boiling: "-62°C",
        row: 6,
        col: 18
    },
    {
        number: 87,
        symbol: "Fr",
        name: "Frâncio",
        mass: "223",
        category: "alkali-metal",
        config: "[Rn] 7s¹",
        state: "Sólido",
        density: "1.87 g/cm³",
        melting: "27°C",
        boiling: "677°C",
        row: 7,
        col: 1
    },
    {
        number: 88,
        symbol: "Ra",
        name: "Rádio",
        mass: "226",
        category: "alkaline-earth-metal",
        config: "[Rn] 7s²",
        state: "Sólido",
        density: "5.5 g/cm³",
        melting: "696°C",
        boiling: "1737°C",
        row: 7,
        col: 2
    },
    {
        number: 89,
        symbol: "Ac",
        name: "Actínio",
        mass: "227",
        category: "actinide",
        config: "[Rn] 6d¹ 7s²",
        state: "Sólido",
        density: "10.07 g/cm³",
        melting: "1051°C",
        boiling: "3198°C",
        row: 9,
        col: 3
    },
    {
        number: 90,
        symbol: "Th",
        name: "Tório",
        mass: "232.04",
        category: "actinide",
        config: "[Rn] 6d² 7s²",
        state: "Sólido",
        density: "11.72 g/cm³",
        melting: "1750°C",
        boiling: "4788°C",
        row: 9,
        col: 4
    },
    {
        number: 91,
        symbol: "Pa",
        name: "Protactínio",
        mass: "231.04",
        category: "actinide",
        config: "[Rn] 5f² 6d¹ 7s²",
        state: "Sólido",
        density: "15.37 g/cm³",
        melting: "1572°C",
        boiling: "4000°C",
        row: 9,
        col: 5
    },
    {
        number: 92,
        symbol: "U",
        name: "Urânio",
        mass: "238.03",
        category: "actinide",
        config: "[Rn] 5f³ 6d¹ 7s²",
        state: "Sólido",
        density: "18.95 g/cm³",
        melting: "1135°C",
        boiling: "4131°C",
        row: 9,
        col: 6
    },
    {
        number: 93,
        symbol: "Np",
        name: "Netúnio",
        mass: "237",
        category: "actinide",
        config: "[Rn] 5f⁴ 6d¹ 7s²",
        state: "Sólido",
        density: "20.25 g/cm³",
        melting: "644°C",
        boiling: "4000°C",
        row: 9,
        col: 7
    },
    {
        number: 94,
        symbol: "Pu",
        name: "Plutônio",
        mass: "244",
        category: "actinide",
        config: "[Rn] 5f⁶ 7s²",
        state: "Sólido",
        density: "19.84 g/cm³",
        melting: "640°C",
        boiling: "3228°C",
        row: 9,
        col: 8
    },
    {
        number: 95,
        symbol: "Am",
        name: "Amerício",
        mass: "243",
        category: "actinide",
        config: "[Rn] 5f⁷ 7s²",
        state: "Sólido",
        density: "13.69 g/cm³",
        melting: "1176°C",
        boiling: "2607°C",
        row: 9,
        col: 9
    },
    {
        number: 96,
        symbol: "Cm",
        name: "Cúrio",
        mass: "247",
        category: "actinide",
        config: "[Rn] 5f⁷ 6d¹ 7s²",
        state: "Sólido",
        density: "13.51 g/cm³",
        melting: "1345°C",
        boiling: "3110°C",
        row: 9,
        col: 10
    },
    {
        number: 97,
        symbol: "Bk",
        name: "Berquélio",
        mass: "247",
        category: "actinide",
        config: "[Rn] 5f⁹ 7s²",
        state: "Sólido",
        density: "14.79 g/cm³",
        melting: "1050°C",
        boiling: "2627°C",
        row: 9,
        col: 11
    },
    {
        number: 98,
        symbol: "Cf",
        name: "Califórnio",
        mass: "251",
        category: "actinide",
        config: "[Rn] 5f¹⁰ 7s²",
        state: "Sólido",
        density: "15.1 g/cm³",
        melting: "900°C",
        boiling: "1743°C",
        row: 9,
        col: 12
    },
    {
        number: 99,
        symbol: "Es",
        name: "Einstênio",
        mass: "252",
        category: "actinide",
        config: "[Rn] 5f¹¹ 7s²",
        state: "Sólido",
        density: "8.84 g/cm³",
        melting: "860°C",
        boiling: "1130°C",
        row: 9,
        col: 13
    },
    {
        number: 100,
        symbol: "Fm",
        name: "Férmio",
        mass: "257",
        category: "actinide",
        config: "[Rn] 5f¹² 7s²",
        state: "Sólido",
        density: "9.7 g/cm³",
        melting: "1527°C",
        boiling: "N/A",
        row: 9,
        col: 14
    },
    {
        number: 101,
        symbol: "Md",
        name: "Mendelévio",
        mass: "258",
        category: "actinide",
        config: "[Rn] 5f¹³ 7s²",
        state: "Sólido",
        density: "10.3 g/cm³",
        melting: "827°C",
        boiling: "N/A",
        row: 9,
        col: 15
    },
    {
        number: 102,
        symbol: "No",
        name: "Nobélio",
        mass: "259",
        category: "actinide",
        config: "[Rn] 5f¹⁴ 7s²",
        state: "Sólido",
        density: "9.9 g/cm³",
        melting: "827°C",
        boiling: "N/A",
        row: 9,
        col: 16
    },
    {
        number: 103,
        symbol: "Lr",
        name: "Laurêncio",
        mass: "262",
        category: "actinide",
        config: "[Rn] 5f¹⁴ 7s² 7p¹",
        state: "Sólido",
        density: "15.6 g/cm³",
        melting: "1627°C",
        boiling: "N/A",
        row: 9,
        col: 17
    },
    {
        number: 104,
        symbol: "Rf",
        name: "Rutherfórdio",
        mass: "267",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d² 7s²",
        state: "Sólido",
        density: "23 g/cm³",
        melting: "2100°C",
        boiling: "5500°C",
        row: 7,
        col: 4
    },
    {
        number: 105,
        symbol: "Db",
        name: "Dúbnio",
        mass: "268",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d³ 7s²",
        state: "Sólido",
        density: "29 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 5
    },
    {
        number: 106,
        symbol: "Sg",
        name: "Seabórgio",
        mass: "269",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁴ 7s²",
        state: "Sólido",
        density: "35 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 6
    },
    {
        number: 107,
        symbol: "Bh",
        name: "Bóhrio",
        mass: "270",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁵ 7s²",
        state: "Sólido",
        density: "37 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 7
    },
    {
        number: 108,
        symbol: "Hs",
        name: "Hássio",
        mass: "277",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁶ 7s²",
        state: "Sólido",
        density: "40 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 8
    },
    {
        number: 109,
        symbol: "Mt",
        name: "Meitnério",
        mass: "278",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁷ 7s²",
        state: "Sólido",
        density: "37 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 9
    },
    {
        number: 110,
        symbol: "Ds",
        name: "Darmstádtio",
        mass: "281",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁸ 7s²",
        state: "Sólido",
        density: "34 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 10
    },
    {
        number: 111,
        symbol: "Rg",
        name: "Roentgênio",
        mass: "282",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d⁹ 7s²",
        state: "Sólido",
        density: "28 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 11
    },
    {
        number: 112,
        symbol: "Cn",
        name: "Copernício",
        mass: "285",
        category: "transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
        state: "Sólido",
        density: "23 g/cm³",
        melting: "N/A",
        boiling: "N/A",
        row: 7,
        col: 12
    },
    {
        number: 113,
        symbol: "Nh",
        name: "Nihônio",
        mass: "286",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
        state: "Sólido",
        density: "16 g/cm³",
        melting: "700°C",
        boiling: "1400°C",
        row: 7,
        col: 13
    },
    {
        number: 114,
        symbol: "Fl",
        name: "Fleróvio",
        mass: "289",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
        state: "Sólido",
        density: "14 g/cm³",
        melting: "200°C",
        boiling: "380°C",
        row: 7,
        col: 14
    },
    {
        number: 115,
        symbol: "Mc",
        name: "Moscóvio",
        mass: "290",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
        state: "Sólido",
        density: "13.5 g/cm³",
        melting: "700°C",
        boiling: "1400°C",
        row: 7,
        col: 15
    },
    {
        number: 116,
        symbol: "Lv",
        name: "Livermório",
        mass: "293",
        category: "post-transition-metal",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
        state: "Sólido",
        density: "12.9 g/cm³",
        melting: "708°C",
        boiling: "1085°C",
        row: 7,
        col: 16
    },
    {
        number: 117,
        symbol: "Ts",
        name: "Tenesso",
        mass: "294",
        category: "halogen",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
        state: "Sólido",
        density: "7.2 g/cm³",
        melting: "723°C",
        boiling: "883°C",
        row: 7,
        col: 17
    },
    {
        number: 118,
        symbol: "Og",
        name: "Oganessônio",
        mass: "294",
        category: "noble-gas",
        config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
        state: "Gás",
        density: "4.95 g/L",
        melting: "52°C",
        boiling: "177°C",
        row: 7,
        col: 18
    }
];

// Mapeamento de categorias para nomes em português
const categoryNames = {
    'alkali-metal': 'Metal Alcalino',
    'alkaline-earth-metal': 'Metal Alcalino-terroso',
    'transition-metal': 'Metal de Transição',
    'post-transition-metal': 'Metal Pós-transição',
    'metalloid': 'Metaloide',
    'nonmetal': 'Não Metal',
    'halogen': 'Halogênio',
    'noble-gas': 'Gás Nobre',
    'lanthanide': 'Lantanídeo',
    'actinide': 'Actinídeo'
};

// Dados de NOX (Estados de Oxidação) dos elementos
const noxData = {
    1: { nox: ["-1", "+1"], common: "+1", explanation: "O hidrogênio pode perder seu único elétron formando H⁺ ou ganhar um elétron formando H⁻ (em hidretos metálicos)." },
    2: { nox: ["0"], common: "0", explanation: "O hélio é um gás nobre com configuração eletrônica estável, não forma compostos químicos comuns." },
    3: { nox: ["+1"], common: "+1", explanation: "O lítio perde facilmente seu elétron de valência, formando o íon Li⁺." },
    4: { nox: ["+2"], common: "+2", explanation: "O berílio perde seus dois elétrons de valência, formando o íon Be²⁺." },
    5: { nox: ["-3", "+3"], common: "+3", explanation: "O boro pode formar compostos covalentes perdendo 3 elétrons ou compartilhando-os." },
    6: { nox: ["-4", "-3", "-2", "-1", "0", "+1", "+2", "+3", "+4"], common: "+4", explanation: "O carbono apresenta grande versatilidade, podendo formar 4 ligações covalentes." },
    7: { nox: ["-3", "-2", "-1", "0", "+1", "+2", "+3", "+4", "+5"], common: "-3", explanation: "O nitrogênio tende a completar seu octeto ganhando 3 elétrons, mas pode apresentar vários NOX." },
    8: { nox: ["-2", "-1", "0", "+1", "+2"], common: "-2", explanation: "O oxigênio tende a ganhar 2 elétrons completando seu octeto, exceto em peróxidos (-1)." },
    9: { nox: ["-1", "0"], common: "-1", explanation: "O flúor é o mais eletronegativo, sempre -1 em compostos (exceto F₂)." },
    10: { nox: ["0"], common: "0", explanation: "O neônio é um gás nobre, não forma compostos químicos comuns." },
    11: { nox: ["+1"], common: "+1", explanation: "O sódio perde facilmente seu elétron de valência, formando Na⁺." },
    12: { nox: ["+2"], common: "+2", explanation: "O magnésio perde seus dois elétrons de valência, formando Mg²⁺." },
    13: { nox: ["+3"], common: "+3", explanation: "O alumínio perde seus três elétrons de valência, formando Al³⁺." },
    14: { nox: ["-4", "+2", "+4"], common: "+4", explanation: "O silício forma principalmente compostos covalentes, especialmente SiO₄⁴⁻." },
    15: { nox: ["-3", "+1", "+3", "+5"], common: "-3", explanation: "O fósforo pode ganhar 3 elétrons ou usar diferentes orbitais d para oxidações positivas." },
    16: { nox: ["-2", "+2", "+4", "+6"], common: "-2", explanation: "O enxofre tende a ganhar 2 elétrons, mas pode usar orbitais d para NOX positivos." },
    17: { nox: ["-1", "+1", "+3", "+5", "+7"], common: "-1", explanation: "O cloro tende a ganhar 1 elétron, mas pode usar orbitais d para NOX positivos." },
    18: { nox: ["0"], common: "0", explanation: "O argônio é um gás nobre, não forma compostos químicos comuns." },
    19: { nox: ["+1"], common: "+1", explanation: "O potássio perde facilmente seu elétron de valência, formando K⁺." },
    20: { nox: ["+2"], common: "+2", explanation: "O cálcio perde seus dois elétrons de valência, formando Ca²⁺." },
    21: { nox: ["+3"], common: "+3", explanation: "O escândio forma principalmente o íon Sc³⁺." },
    22: { nox: ["+2", "+3", "+4"], common: "+4", explanation: "O titânio apresenta múltiplos estados de oxidação, sendo +4 o mais estável." },
    23: { nox: ["+2", "+3", "+4", "+5"], common: "+5", explanation: "O vanádio apresenta vários NOX, sendo +5 comum em vanadatos." },
    24: { nox: ["+2", "+3", "+6"], common: "+3", explanation: "O cromo apresenta NOX +3 (estável) e +6 (em dicromatos)." },
    25: { nox: ["+2", "+3", "+4", "+6", "+7"], common: "+2", explanation: "O manganês apresenta grande variedade de NOX, +7 em permanganatos." },
    26: { nox: ["+2", "+3"], common: "+3", explanation: "O ferro apresenta principalmente NOX +2 e +3, sendo +3 mais estável." },
    27: { nox: ["+2", "+3"], common: "+2", explanation: "O cobalto apresenta NOX +2 (mais comum) e +3." },
    28: { nox: ["+2", "+3"], common: "+2", explanation: "O níquel apresenta principalmente NOX +2, menos comum +3." },
    29: { nox: ["+1", "+2"], common: "+2", explanation: "O cobre apresenta NOX +1 (cuproso) e +2 (cúprico)." },
    30: { nox: ["+2"], common: "+2", explanation: "O zinco perde seus dois elétrons 4s, formando Zn²⁺." },
    31: { nox: ["+3"], common: "+3", explanation: "O gálio perde seus três elétrons de valência, formando Ga³⁺." },
    32: { nox: ["-4", "+2", "+4"], common: "+4", explanation: "O germânio apresenta NOX +4 mais comum, similar ao silício." },
    33: { nox: ["-3", "+3", "+5"], common: "+3", explanation: "O arsênio pode ganhar 3 elétrons ou apresentar NOX positivos." },
    34: { nox: ["-2", "+2", "+4", "+6"], common: "-2", explanation: "O selênio comporta-se similarmente ao enxofre." },
    35: { nox: ["-1", "+1", "+3", "+5", "+7"], common: "-1", explanation: "O bromo comporta-se similarmente ao cloro." },
    36: { nox: ["0", "+2"], common: "0", explanation: "O criptônio raramente forma compostos, exceto alguns com flúor." },
    37: { nox: ["+1"], common: "+1", explanation: "O rubídio perde facilmente seu elétron de valência." },
    38: { nox: ["+2"], common: "+2", explanation: "O estrôncio perde seus dois elétrons de valência." },
    47: { nox: ["+1", "+2"], common: "+1", explanation: "A prata apresenta principalmente NOX +1." },
    48: { nox: ["+2"], common: "+2", explanation: "O cádmio perde seus dois elétrons 5s." },
    50: { nox: ["+2", "+4"], common: "+4", explanation: "O estanho apresenta NOX +2 (estanoso) e +4 (estânico)." },
    53: { nox: ["-1", "+1", "+3", "+5", "+7"], common: "-1", explanation: "O iodo comporta-se como os outros halogênios." },
    54: { nox: ["0", "+2", "+4", "+6"], common: "0", explanation: "O xenônio pode formar alguns compostos, especialmente com flúor." },
    55: { nox: ["+1"], common: "+1", explanation: "O césio perde facilmente seu elétron de valência." },
    56: { nox: ["+2"], common: "+2", explanation: "O bário perde seus dois elétrons de valência." },
    79: { nox: ["+1", "+3"], common: "+3", explanation: "O ouro apresenta NOX +1 (auroso) e +3 (áurico)." },
    80: { nox: ["+1", "+2"], common: "+2", explanation: "O mercúrio apresenta NOX +1 (mercuroso) e +2 (mercúrico)." },
    82: { nox: ["+2", "+4"], common: "+2", explanation: "O chumbo apresenta NOX +2 (plumboso) e +4 (plúmbico)." }
};

// Função para aplicar dados de NOX aos elementos
function applyNoxData() {
    elementsData.forEach(element => {
        const noxInfo = noxData[element.number];
        if (noxInfo) {
            element.nox = noxInfo.nox;
            element.commonNox = noxInfo.common;
            element.noxExplanation = noxInfo.explanation;
        } else {
            // Valores padrão para elementos sem dados específicos
            element.nox = ["0"];
            element.commonNox = "0";
            element.noxExplanation = "Dados de NOX não disponíveis para este elemento.";
        }
    });
}

// Aplicar dados de NOX automaticamente
applyNoxData();
